// XXX/src/main/webapp/app/entities/hotel-room/update/hotel-room-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { FormBuilder } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { finalize, map } from 'rxjs/operators';

import { IHotelRoom, HotelRoom } from '../hotel-room.model';
import { HotelRoomService } from '../service/hotel-room.service';
import { IHotelCompany } from 'app/entities/hotel-company/hotel-company.model';
import { HotelCompanyService } from 'app/entities/hotel-company/service/hotel-company.service';

@Component({
  selector: 'jhi-hotel-room-update',
  templateUrl: './hotel-room-update.component.html',
})
export class HotelRoomUpdateComponent implements OnInit {
  isSaving = false;

  hotelCompaniesSharedCollection: IHotelCompany[] = [];

  editForm = this.fb.group({
    id: [],
    code: [],
    sleeps: [],
    boodked: [],
    duration: [],
    price: [],
    hotelCo: [],
  });

  constructor(
    protected hotelRoomService: HotelRoomService,
    protected hotelCompanyService: HotelCompanyService,
    protected activatedRoute: ActivatedRoute,
    protected fb: FormBuilder
  ) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ hotelRoom }) => {
      this.updateForm(hotelRoom);

      this.loadRelationshipsOptions();
    });
  }

  previousState(): void {
    window.history.back();
  }

  save(): void {
    this.isSaving = true;
    const hotelRoom = this.createFromForm();
    if (hotelRoom.id !== undefined) {
      this.subscribeToSaveResponse(this.hotelRoomService.update(hotelRoom));
    } else {
      this.subscribeToSaveResponse(this.hotelRoomService.create(hotelRoom));
    }
  }

  trackHotelCompanyById(index: number, item: IHotelCompany): number {
    return item.id!;
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<IHotelRoom>>): void {
    result.pipe(finalize(() => this.onSaveFinalize())).subscribe(
      () => this.onSaveSuccess(),
      () => this.onSaveError()
    );
  }

  protected onSaveSuccess(): void {
    this.previousState();
  }

  protected onSaveError(): void {
    // Api for inheritance.
  }

  protected onSaveFinalize(): void {
    this.isSaving = false;
  }

  protected updateForm(hotelRoom: IHotelRoom): void {
    this.editForm.patchValue({
      id: hotelRoom.id,
      code: hotelRoom.code,
      sleeps: hotelRoom.sleeps,
      boodked: hotelRoom.boodked,
      duration: hotelRoom.duration,
      price: hotelRoom.price,
      hotelCo: hotelRoom.hotelCo,
    });

    this.hotelCompaniesSharedCollection = this.hotelCompanyService.addHotelCompanyToCollectionIfMissing(
      this.hotelCompaniesSharedCollection,
      hotelRoom.hotelCo
    );
  }

  protected loadRelationshipsOptions(): void {
    this.hotelCompanyService
      .query()
      .pipe(map((res: HttpResponse<IHotelCompany[]>) => res.body ?? []))
      .pipe(
        map((hotelCompanies: IHotelCompany[]) =>
          this.hotelCompanyService.addHotelCompanyToCollectionIfMissing(hotelCompanies, this.editForm.get('hotelCo')!.value)
        )
      )
      .subscribe((hotelCompanies: IHotelCompany[]) => (this.hotelCompaniesSharedCollection = hotelCompanies));
  }

  protected createFromForm(): IHotelRoom {
    return {
      ...new HotelRoom(),
      id: this.editForm.get(['id'])!.value,
      code: this.editForm.get(['code'])!.value,
      sleeps: this.editForm.get(['sleeps'])!.value,
      boodked: this.editForm.get(['boodked'])!.value,
      duration: this.editForm.get(['duration'])!.value,
      price: this.editForm.get(['price'])!.value,
      hotelCo: this.editForm.get(['hotelCo'])!.value,
    };
  }
}

<div class="row justify-content-center">
  <div class="col-8">
    <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
      <h2
        id="jhi-hotel-room-heading"
        data-cy="HotelRoomCreateUpdateHeading"
        jhiTranslate="travelTutorialCompleteApp.hotelRoom.home.createOrEditLabel"
      >
        Create or edit a Hotel Room
      </h2>

      <div>
        <jhi-alert-error></jhi-alert-error>

        <div class="form-group" [hidden]="editForm.get('id')!.value == null">
          <label class="form-control-label" jhiTranslate="global.field.id" for="field_id">ID</label>
          <input type="number" class="form-control" name="id" id="field_id" data-cy="id" formControlName="id" [readonly]="true" />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="travelTutorialCompleteApp.hotelRoom.code" for="field_code">Code</label>
          <input type="text" class="form-control" name="code" id="field_code" data-cy="code" formControlName="code" />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="travelTutorialCompleteApp.hotelRoom.sleeps" for="field_sleeps">Sleeps</label>
          <input type="number" class="form-control" name="sleeps" id="field_sleeps" data-cy="sleeps" formControlName="sleeps" />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="travelTutorialCompleteApp.hotelRoom.boodked" for="field_boodked">Boodked</label>
          <div class="input-group">
            <input
              id="field_boodked"
              data-cy="boodked"
              type="text"
              class="form-control"
              name="boodked"
              ngbDatepicker
              #boodkedDp="ngbDatepicker"
              formControlName="boodked"
            />
            <span class="input-group-append">
              <button type="button" class="btn btn-secondary" (click)="boodkedDp.toggle()"><fa-icon icon="calendar-alt"></fa-icon></button>
            </span>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="travelTutorialCompleteApp.hotelRoom.duration" for="field_duration"
            >Duration</label
          >
          <input type="number" class="form-control" name="duration" id="field_duration" data-cy="duration" formControlName="duration" />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="travelTutorialCompleteApp.hotelRoom.price" for="field_price">Price</label>
          <input type="number" class="form-control" name="price" id="field_price" data-cy="price" formControlName="price" />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="travelTutorialCompleteApp.hotelRoom.hotelCo" for="field_hotelCo">Hotel Co</label>
          <select class="form-control" id="field_hotelCo" data-cy="hotelCo" name="hotelCo" formControlName="hotelCo">
            <option [ngValue]="null"></option>
            <option
              [ngValue]="hotelCompanyOption.id === editForm.get('hotelCo')!.value?.id ? editForm.get('hotelCo')!.value : hotelCompanyOption"
              *ngFor="let hotelCompanyOption of hotelCompaniesSharedCollection; trackBy: trackHotelCompanyById"
            >
              {{ hotelCompanyOption.name }}
            </option>
          </select>
        </div>
      </div>

      <div>
        <button type="button" id="cancel-save" class="btn btn-secondary" (click)="previousState()">
          <fa-icon icon="ban"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
        </button>

        <button
          type="submit"
          id="save-entity"
          data-cy="entityCreateSaveButton"
          [disabled]="editForm.invalid || isSaving"
          class="btn btn-primary"
        >
          <fa-icon icon="save"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
        </button>
      </div>
    </form>
  </div>
</div>

// travelTutorialCOMPLETE/src/main/webapp/app/entities/hotel-room/hotel-room-update.vue
<template>
  <div class="row justify-content-center">
    <div class="col-8">
      <form name="editForm" role="form" novalidate v-on:submit.prevent="save()">
        <h2
          id="travelTutorialCompleteApp.hotelRoom.home.createOrEditLabel"
          data-cy="HotelRoomCreateUpdateHeading"
          v-text="$t('travelTutorialCompleteApp.hotelRoom.home.createOrEditLabel')"
        >
          Create or edit a HotelRoom
        </h2>
        <div>
          <div class="form-group" v-if="hotelRoom.id">
            <label for="id" v-text="$t('global.field.id')">ID</label>
            <input type="text" class="form-control" id="id" name="id" v-model="hotelRoom.id" readonly />
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('travelTutorialCompleteApp.hotelRoom.code')" for="hotel-room-code">Code</label>
            <input
              type="text"
              class="form-control"
              name="code"
              id="hotel-room-code"
              data-cy="code"
              :class="{ valid: !$v.hotelRoom.code.$invalid, invalid: $v.hotelRoom.code.$invalid }"
              v-model="$v.hotelRoom.code.$model"
            />
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('travelTutorialCompleteApp.hotelRoom.sleeps')" for="hotel-room-sleeps"
              >Sleeps</label
            >
            <input
              type="number"
              class="form-control"
              name="sleeps"
              id="hotel-room-sleeps"
              data-cy="sleeps"
              :class="{ valid: !$v.hotelRoom.sleeps.$invalid, invalid: $v.hotelRoom.sleeps.$invalid }"
              v-model.number="$v.hotelRoom.sleeps.$model"
            />
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('travelTutorialCompleteApp.hotelRoom.boodked')" for="hotel-room-boodked"
              >Boodked</label
            >
            <b-input-group class="mb-3">
              <b-input-group-prepend>
                <b-form-datepicker
                  aria-controls="hotel-room-boodked"
                  v-model="$v.hotelRoom.boodked.$model"
                  name="boodked"
                  class="form-control"
                  :locale="currentLanguage"
                  button-only
                  today-button
                  reset-button
                  close-button
                >
                </b-form-datepicker>
              </b-input-group-prepend>
              <b-form-input
                id="hotel-room-boodked"
                data-cy="boodked"
                type="text"
                class="form-control"
                name="boodked"
                :class="{ valid: !$v.hotelRoom.boodked.$invalid, invalid: $v.hotelRoom.boodked.$invalid }"
                v-model="$v.hotelRoom.boodked.$model"
              />
            </b-input-group>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('travelTutorialCompleteApp.hotelRoom.duration')" for="hotel-room-duration"
              >Duration</label
            >
            <input
              type="number"
              class="form-control"
              name="duration"
              id="hotel-room-duration"
              data-cy="duration"
              :class="{ valid: !$v.hotelRoom.duration.$invalid, invalid: $v.hotelRoom.duration.$invalid }"
              v-model.number="$v.hotelRoom.duration.$model"
            />
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('travelTutorialCompleteApp.hotelRoom.price')" for="hotel-room-price">Price</label>
            <input
              type="number"
              class="form-control"
              name="price"
              id="hotel-room-price"
              data-cy="price"
              :class="{ valid: !$v.hotelRoom.price.$invalid, invalid: $v.hotelRoom.price.$invalid }"
              v-model.number="$v.hotelRoom.price.$model"
            />
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('travelTutorialCompleteApp.hotelRoom.hotelCo')" for="hotel-room-hotelCo"
              >Hotel Co</label
            >
            <select class="form-control" id="hotel-room-hotelCo" data-cy="hotelCo" name="hotelCo" v-model="hotelRoom.hotelCo">
              <option v-bind:value="null"></option>
              <option
                v-bind:value="hotelRoom.hotelCo && hotelCompanyOption.id === hotelRoom.hotelCo.id ? hotelRoom.hotelCo : hotelCompanyOption"
                v-for="hotelCompanyOption in hotelCompanies"
                :key="hotelCompanyOption.id"
              >
                {{ hotelCompanyOption.name }}
              </option>
            </select>
          </div>
        </div>
        <div>
          <button type="button" id="cancel-save" class="btn btn-secondary" v-on:click="previousState()">
            <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.cancel')">Cancel</span>
          </button>
          <button
            type="submit"
            id="save-entity"
            data-cy="entityCreateSaveButton"
            :disabled="$v.hotelRoom.$invalid || isSaving"
            class="btn btn-primary"
          >
            <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.save')">Save</span>
          </button>
        </div>
      </form>
    </div>
  </div>
</template>
<script lang="ts" src="./hotel-room-update.component.ts"></script>
