// XXX/src/main/webapp/app/entities/car-rental-company/list/car-rental-company.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { ICarRentalCompany } from '../car-rental-company.model';
import { CarRentalCompanyService } from '../service/car-rental-company.service';
import { CarRentalCompanyDeleteDialogComponent } from '../delete/car-rental-company-delete-dialog.component';

@Component({
  selector: 'jhi-car-rental-company',
  templateUrl: './car-rental-company.component.html',
})
export class CarRentalCompanyComponent implements OnInit {
  carRentalCompanies?: ICarRentalCompany[];
  isLoading = false;

  constructor(protected carRentalCompanyService: CarRentalCompanyService, protected modalService: NgbModal) {}

  loadAll(): void {
    this.isLoading = true;

    this.carRentalCompanyService.query().subscribe(
      (res: HttpResponse<ICarRentalCompany[]>) => {
        this.isLoading = false;
        this.carRentalCompanies = res.body ?? [];
      },
      () => {
        this.isLoading = false;
      }
    );
  }

  ngOnInit(): void {
    this.loadAll();
  }

  trackId(index: number, item: ICarRentalCompany): number {
    return item.id!;
  }

  delete(carRentalCompany: ICarRentalCompany): void {
    const modalRef = this.modalService.open(CarRentalCompanyDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.carRentalCompany = carRentalCompany;
    // unsubscribe not needed because closed completes on modal close
    modalRef.closed.subscribe(reason => {
      if (reason === 'deleted') {
        this.loadAll();
      }
    });
  }
}

<div>
  <h2 id="page-heading" data-cy="CarRentalCompanyHeading">
    <span jhiTranslate="travelTutorialCompleteApp.carRentalCompany.home.title">Car Rental Companies</span>

    <div class="d-flex justify-content-end">
      <button class="btn btn-info mr-2" (click)="loadAll()" [disabled]="isLoading">
        <fa-icon icon="sync" [spin]="isLoading"></fa-icon>
        <span jhiTranslate="travelTutorialCompleteApp.carRentalCompany.home.refreshListLabel">Refresh List</span>
      </button>

      <button
        id="jh-create-entity"
        data-cy="entityCreateButton"
        class="btn btn-primary jh-create-entity create-car-rental-company"
        [routerLink]="['/car-rental-company/new']"
      >
        <fa-icon icon="plus"></fa-icon>
        <span jhiTranslate="travelTutorialCompleteApp.carRentalCompany.home.createLabel"> Create a new Car Rental Company </span>
      </button>
    </div>
  </h2>

  <jhi-alert-error></jhi-alert-error>

  <jhi-alert></jhi-alert>

  <div class="alert alert-warning" id="no-result" *ngIf="carRentalCompanies?.length === 0">
    <span jhiTranslate="travelTutorialCompleteApp.carRentalCompany.home.notFound">No carRentalCompanies found</span>
  </div>

  <div class="table-responsive" id="entities" *ngIf="carRentalCompanies && carRentalCompanies.length > 0">
    <table class="table table-striped" aria-describedby="page-heading">
      <thead>
        <tr>
          <th scope="col"><span jhiTranslate="global.field.id">ID</span></th>
          <th scope="col"><span jhiTranslate="travelTutorialCompleteApp.carRentalCompany.name">Name</span></th>
          <th scope="col"><span jhiTranslate="travelTutorialCompleteApp.carRentalCompany.place">Place</span></th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let carRentalCompany of carRentalCompanies; trackBy: trackId" data-cy="entityTable">
          <td>
            <a [routerLink]="['/car-rental-company', carRentalCompany.id, 'view']">{{ carRentalCompany.id }}</a>
          </td>
          <td>{{ carRentalCompany.name }}</td>
          <td>{{ carRentalCompany.place }}</td>
          <td class="text-right">
            <div class="btn-group">
              <button
                type="submit"
                [routerLink]="['/car-rental-company', carRentalCompany.id, 'view']"
                class="btn btn-info btn-sm"
                data-cy="entityDetailsButton"
              >
                <fa-icon icon="eye"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
              </button>

              <button
                type="submit"
                [routerLink]="['/car-rental-company', carRentalCompany.id, 'edit']"
                class="btn btn-primary btn-sm"
                data-cy="entityEditButton"
              >
                <fa-icon icon="pencil-alt"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
              </button>

              <button type="submit" (click)="delete(carRentalCompany)" class="btn btn-danger btn-sm" data-cy="entityDeleteButton">
                <fa-icon icon="times"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
              </button>
            </div>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

// travelTutorialENTITIES2/src/main/webapp/app/entities/car-rental-company/car-rental-company.vue
<template>
  <div>
    <h2 id="page-heading" data-cy="CarRentalCompanyHeading">
      <span v-text="$t('travelTutorialEntities2App.carRentalCompany.home.title')" id="car-rental-company-heading"
        >Car Rental Companies</span
      >
      <div class="d-flex justify-content-end">
        <button class="btn btn-info mr-2" v-on:click="handleSyncList" :disabled="isFetching">
          <font-awesome-icon icon="sync" :spin="isFetching"></font-awesome-icon>
          <span v-text="$t('travelTutorialEntities2App.carRentalCompany.home.refreshListLabel')">Refresh List</span>
        </button>
        <router-link :to="{ name: 'CarRentalCompanyCreate' }" custom v-slot="{ navigate }">
          <button
            @click="navigate"
            id="jh-create-entity"
            data-cy="entityCreateButton"
            class="btn btn-primary jh-create-entity create-car-rental-company"
          >
            <font-awesome-icon icon="plus"></font-awesome-icon>
            <span v-text="$t('travelTutorialEntities2App.carRentalCompany.home.createLabel')"> Create a new Car Rental Company </span>
          </button>
        </router-link>
      </div>
    </h2>
    <br />
    <div class="alert alert-warning" v-if="!isFetching && carRentalCompanies && carRentalCompanies.length === 0">
      <span v-text="$t('travelTutorialEntities2App.carRentalCompany.home.notFound')">No carRentalCompanies found</span>
    </div>
    <div class="table-responsive" v-if="carRentalCompanies && carRentalCompanies.length > 0">
      <table class="table table-striped" aria-describedby="carRentalCompanies">
        <thead>
          <tr>
            <th scope="row"><span v-text="$t('global.field.id')">ID</span></th>
            <th scope="row"><span v-text="$t('travelTutorialEntities2App.carRentalCompany.name')">Name</span></th>
            <th scope="row"><span v-text="$t('travelTutorialEntities2App.carRentalCompany.code')">Code</span></th>
            <th scope="row"></th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="carRentalCompany in carRentalCompanies" :key="carRentalCompany.id" data-cy="entityTable">
            <td>
              <router-link :to="{ name: 'CarRentalCompanyView', params: { carRentalCompanyId: carRentalCompany.id } }">{{
                carRentalCompany.id
              }}</router-link>
            </td>
            <td>{{ carRentalCompany.name }}</td>
            <td>{{ carRentalCompany.code }}</td>
            <td class="text-right">
              <div class="btn-group">
                <router-link
                  :to="{ name: 'CarRentalCompanyView', params: { carRentalCompanyId: carRentalCompany.id } }"
                  custom
                  v-slot="{ navigate }"
                >
                  <button @click="navigate" class="btn btn-info btn-sm details" data-cy="entityDetailsButton">
                    <font-awesome-icon icon="eye"></font-awesome-icon>
                    <span class="d-none d-md-inline" v-text="$t('entity.action.view')">View</span>
                  </button>
                </router-link>
                <router-link
                  :to="{ name: 'CarRentalCompanyEdit', params: { carRentalCompanyId: carRentalCompany.id } }"
                  custom
                  v-slot="{ navigate }"
                >
                  <button @click="navigate" class="btn btn-primary btn-sm edit" data-cy="entityEditButton">
                    <font-awesome-icon icon="pencil-alt"></font-awesome-icon>
                    <span class="d-none d-md-inline" v-text="$t('entity.action.edit')">Edit</span>
                  </button>
                </router-link>
                <b-button
                  v-on:click="prepareRemove(carRentalCompany)"
                  variant="danger"
                  class="btn btn-sm"
                  data-cy="entityDeleteButton"
                  v-b-modal.removeEntity
                >
                  <font-awesome-icon icon="times"></font-awesome-icon>
                  <span class="d-none d-md-inline" v-text="$t('entity.action.delete')">Delete</span>
                </b-button>
              </div>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
    <b-modal ref="removeEntity" id="removeEntity">
      <span slot="modal-title"
        ><span
          id="travelTutorialEntities2App.carRentalCompany.delete.question"
          data-cy="carRentalCompanyDeleteDialogHeading"
          v-text="$t('entity.delete.title')"
          >Confirm delete operation</span
        ></span
      >
      <div class="modal-body">
        <p
          id="jhi-delete-carRentalCompany-heading"
          v-text="$t('travelTutorialEntities2App.carRentalCompany.delete.question', { id: removeId })"
        >
          Are you sure you want to delete this Car Rental Company?
        </p>
      </div>
      <div slot="modal-footer">
        <button type="button" class="btn btn-secondary" v-text="$t('entity.action.cancel')" v-on:click="closeDialog()">Cancel</button>
        <button
          type="button"
          class="btn btn-primary"
          id="jhi-confirm-delete-carRentalCompany"
          data-cy="entityConfirmDeleteButton"
          v-text="$t('entity.action.delete')"
          v-on:click="removeCarRentalCompany()"
        >
          Delete
        </button>
      </div>
    </b-modal>
  </div>
</template>

<script lang="ts" src="./car-rental-company.component.ts"></script>
