// XXX/src/main/webapp/app/entities/car-rental-company/update/car-rental-company-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { FormBuilder } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { finalize } from 'rxjs/operators';

import { ICarRentalCompany, CarRentalCompany } from '../car-rental-company.model';
import { CarRentalCompanyService } from '../service/car-rental-company.service';

@Component({
  selector: 'jhi-car-rental-company-update',
  templateUrl: './car-rental-company-update.component.html',
})
export class CarRentalCompanyUpdateComponent implements OnInit {
  isSaving = false;

  editForm = this.fb.group({
    id: [],
    name: [],
    place: [],
  });

  constructor(
    protected carRentalCompanyService: CarRentalCompanyService,
    protected activatedRoute: ActivatedRoute,
    protected fb: FormBuilder
  ) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ carRentalCompany }) => {
      this.updateForm(carRentalCompany);
    });
  }

  previousState(): void {
    window.history.back();
  }

  save(): void {
    this.isSaving = true;
    const carRentalCompany = this.createFromForm();
    if (carRentalCompany.id !== undefined) {
      this.subscribeToSaveResponse(this.carRentalCompanyService.update(carRentalCompany));
    } else {
      this.subscribeToSaveResponse(this.carRentalCompanyService.create(carRentalCompany));
    }
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<ICarRentalCompany>>): void {
    result.pipe(finalize(() => this.onSaveFinalize())).subscribe(
      () => this.onSaveSuccess(),
      () => this.onSaveError()
    );
  }

  protected onSaveSuccess(): void {
    this.previousState();
  }

  protected onSaveError(): void {
    // Api for inheritance.
  }

  protected onSaveFinalize(): void {
    this.isSaving = false;
  }

  protected updateForm(carRentalCompany: ICarRentalCompany): void {
    this.editForm.patchValue({
      id: carRentalCompany.id,
      name: carRentalCompany.name,
      place: carRentalCompany.place,
    });
  }

  protected createFromForm(): ICarRentalCompany {
    return {
      ...new CarRentalCompany(),
      id: this.editForm.get(['id'])!.value,
      name: this.editForm.get(['name'])!.value,
      place: this.editForm.get(['place'])!.value,
    };
  }
}

<div class="row justify-content-center">
  <div class="col-8">
    <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
      <h2
        id="jhi-car-rental-company-heading"
        data-cy="CarRentalCompanyCreateUpdateHeading"
        jhiTranslate="travelTutorialCompleteApp.carRentalCompany.home.createOrEditLabel"
      >
        Create or edit a Car Rental Company
      </h2>

      <div>
        <jhi-alert-error></jhi-alert-error>

        <div class="form-group" [hidden]="editForm.get('id')!.value == null">
          <label class="form-control-label" jhiTranslate="global.field.id" for="field_id">ID</label>
          <input type="number" class="form-control" name="id" id="field_id" data-cy="id" formControlName="id" [readonly]="true" />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="travelTutorialCompleteApp.carRentalCompany.name" for="field_name">Name</label>
          <input type="text" class="form-control" name="name" id="field_name" data-cy="name" formControlName="name" />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="travelTutorialCompleteApp.carRentalCompany.place" for="field_place">Place</label>
          <input type="text" class="form-control" name="place" id="field_place" data-cy="place" formControlName="place" />
        </div>
      </div>

      <div>
        <button type="button" id="cancel-save" class="btn btn-secondary" (click)="previousState()">
          <fa-icon icon="ban"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
        </button>

        <button
          type="submit"
          id="save-entity"
          data-cy="entityCreateSaveButton"
          [disabled]="editForm.invalid || isSaving"
          class="btn btn-primary"
        >
          <fa-icon icon="save"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
        </button>
      </div>
    </form>
  </div>
</div>

// travelTutorialENTITIES2/src/main/webapp/app/entities/car-rental-company/car-rental-company-update.vue
<template>
  <div class="row justify-content-center">
    <div class="col-8">
      <form name="editForm" role="form" novalidate v-on:submit.prevent="save()">
        <h2
          id="travelTutorialEntities2App.carRentalCompany.home.createOrEditLabel"
          data-cy="CarRentalCompanyCreateUpdateHeading"
          v-text="$t('travelTutorialEntities2App.carRentalCompany.home.createOrEditLabel')"
        >
          Create or edit a CarRentalCompany
        </h2>
        <div>
          <div class="form-group" v-if="carRentalCompany.id">
            <label for="id" v-text="$t('global.field.id')">ID</label>
            <input type="text" class="form-control" id="id" name="id" v-model="carRentalCompany.id" readonly />
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('travelTutorialEntities2App.carRentalCompany.name')" for="car-rental-company-name"
              >Name</label
            >
            <input
              type="text"
              class="form-control"
              name="name"
              id="car-rental-company-name"
              data-cy="name"
              :class="{ valid: !$v.carRentalCompany.name.$invalid, invalid: $v.carRentalCompany.name.$invalid }"
              v-model="$v.carRentalCompany.name.$model"
            />
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('travelTutorialEntities2App.carRentalCompany.code')" for="car-rental-company-code"
              >Code</label
            >
            <input
              type="text"
              class="form-control"
              name="code"
              id="car-rental-company-code"
              data-cy="code"
              :class="{ valid: !$v.carRentalCompany.code.$invalid, invalid: $v.carRentalCompany.code.$invalid }"
              v-model="$v.carRentalCompany.code.$model"
            />
          </div>
        </div>
        <div>
          <button type="button" id="cancel-save" class="btn btn-secondary" v-on:click="previousState()">
            <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.cancel')">Cancel</span>
          </button>
          <button
            type="submit"
            id="save-entity"
            data-cy="entityCreateSaveButton"
            :disabled="$v.carRentalCompany.$invalid || isSaving"
            class="btn btn-primary"
          >
            <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.save')">Save</span>
          </button>
        </div>
      </form>
    </div>
  </div>
</template>
<script lang="ts" src="./car-rental-company-update.component.ts"></script>
