// travelTutorialCOMPLETE/src/main/webapp/app/entities/hotel-company/hotel-company-update.vue
<template>
  <div class="row justify-content-center">
    <div class="col-8">
      <form name="editForm" role="form" novalidate v-on:submit.prevent="save()">
        <h2
          id="travelTutorialCompleteApp.hotelCompany.home.createOrEditLabel"
          data-cy="HotelCompanyCreateUpdateHeading"
          v-text="$t('travelTutorialCompleteApp.hotelCompany.home.createOrEditLabel')"
        >
          Create or edit a HotelCompany
        </h2>
        <div>
          <div class="form-group" v-if="hotelCompany.id">
            <label for="id" v-text="$t('global.field.id')">ID</label>
            <input type="text" class="form-control" id="id" name="id" v-model="hotelCompany.id" readonly />
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('travelTutorialCompleteApp.hotelCompany.name')" for="hotel-company-name"
              >Name</label
            >
            <input
              type="text"
              class="form-control"
              name="name"
              id="hotel-company-name"
              data-cy="name"
              :class="{ valid: !$v.hotelCompany.name.$invalid, invalid: $v.hotelCompany.name.$invalid }"
              v-model="$v.hotelCompany.name.$model"
            />
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('travelTutorialCompleteApp.hotelCompany.place')" for="hotel-company-place"
              >Place</label
            >
            <input
              type="text"
              class="form-control"
              name="place"
              id="hotel-company-place"
              data-cy="place"
              :class="{ valid: !$v.hotelCompany.place.$invalid, invalid: $v.hotelCompany.place.$invalid }"
              v-model="$v.hotelCompany.place.$model"
            />
          </div>
        </div>
        <div>
          <button type="button" id="cancel-save" class="btn btn-secondary" v-on:click="previousState()">
            <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.cancel')">Cancel</span>
          </button>
          <button
            type="submit"
            id="save-entity"
            data-cy="entityCreateSaveButton"
            :disabled="$v.hotelCompany.$invalid || isSaving"
            class="btn btn-primary"
          >
            <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.save')">Save</span>
          </button>
        </div>
      </form>
    </div>
  </div>
</template>
<script lang="ts" src="./hotel-company-update.component.ts"></script>

// XXX/src/main/webapp/app/entities/hotel-company/update/hotel-company-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { FormBuilder } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { finalize } from 'rxjs/operators';

import { IHotelCompany, HotelCompany } from '../hotel-company.model';
import { HotelCompanyService } from '../service/hotel-company.service';

@Component({
  selector: 'jhi-hotel-company-update',
  templateUrl: './hotel-company-update.component.html',
})
export class HotelCompanyUpdateComponent implements OnInit {
  isSaving = false;

  editForm = this.fb.group({
    id: [],
    name: [],
    place: [],
  });

  constructor(protected hotelCompanyService: HotelCompanyService, protected activatedRoute: ActivatedRoute, protected fb: FormBuilder) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ hotelCompany }) => {
      this.updateForm(hotelCompany);
    });
  }

  previousState(): void {
    window.history.back();
  }

  save(): void {
    this.isSaving = true;
    const hotelCompany = this.createFromForm();
    if (hotelCompany.id !== undefined) {
      this.subscribeToSaveResponse(this.hotelCompanyService.update(hotelCompany));
    } else {
      this.subscribeToSaveResponse(this.hotelCompanyService.create(hotelCompany));
    }
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<IHotelCompany>>): void {
    result.pipe(finalize(() => this.onSaveFinalize())).subscribe(
      () => this.onSaveSuccess(),
      () => this.onSaveError()
    );
  }

  protected onSaveSuccess(): void {
    this.previousState();
  }

  protected onSaveError(): void {
    // Api for inheritance.
  }

  protected onSaveFinalize(): void {
    this.isSaving = false;
  }

  protected updateForm(hotelCompany: IHotelCompany): void {
    this.editForm.patchValue({
      id: hotelCompany.id,
      name: hotelCompany.name,
      place: hotelCompany.place,
    });
  }

  protected createFromForm(): IHotelCompany {
    return {
      ...new HotelCompany(),
      id: this.editForm.get(['id'])!.value,
      name: this.editForm.get(['name'])!.value,
      place: this.editForm.get(['place'])!.value,
    };
  }
}

<div class="row justify-content-center">
  <div class="col-8">
    <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
      <h2
        id="jhi-hotel-company-heading"
        data-cy="HotelCompanyCreateUpdateHeading"
        jhiTranslate="travelTutorialCompleteApp.hotelCompany.home.createOrEditLabel"
      >
        Create or edit a Hotel Company
      </h2>

      <div>
        <jhi-alert-error></jhi-alert-error>

        <div class="form-group" [hidden]="editForm.get('id')!.value == null">
          <label class="form-control-label" jhiTranslate="global.field.id" for="field_id">ID</label>
          <input type="number" class="form-control" name="id" id="field_id" data-cy="id" formControlName="id" [readonly]="true" />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="travelTutorialCompleteApp.hotelCompany.name" for="field_name">Name</label>
          <input type="text" class="form-control" name="name" id="field_name" data-cy="name" formControlName="name" />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="travelTutorialCompleteApp.hotelCompany.place" for="field_place">Place</label>
          <input type="text" class="form-control" name="place" id="field_place" data-cy="place" formControlName="place" />
        </div>
      </div>

      <div>
        <button type="button" id="cancel-save" class="btn btn-secondary" (click)="previousState()">
          <fa-icon icon="ban"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
        </button>

        <button
          type="submit"
          id="save-entity"
          data-cy="entityCreateSaveButton"
          [disabled]="editForm.invalid || isSaving"
          class="btn btn-primary"
        >
          <fa-icon icon="save"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
        </button>
      </div>
    </form>
  </div>
</div>
