// travelTutorialCOMPLETE/src/main/webapp/app/entities/travel-plan/travel-plan.vue
<template>
  <div>
    <h2 id="page-heading" data-cy="TravelPlanHeading">
      <span v-text="$t('travelTutorialCompleteApp.travelPlan.home.title')" id="travel-plan-heading">Travel Plans</span>
      <div class="d-flex justify-content-end">
        <button class="btn btn-info mr-2" v-on:click="handleSyncList" :disabled="isFetching">
          <font-awesome-icon icon="sync" :spin="isFetching"></font-awesome-icon>
          <span v-text="$t('travelTutorialCompleteApp.travelPlan.home.refreshListLabel')">Refresh List</span>
        </button>
      </div>
    </h2>
    <br />
    <div class="alert alert-warning" v-if="!isFetching && travelPlans && travelPlans.length === 0">
      <span v-text="$t('travelTutorialCompleteApp.travelPlan.home.notFound')">No travelPlans found</span>
    </div>
    <div class="table-responsive" v-if="travelPlans && travelPlans.length > 0">
      <table class="table table-striped" aria-describedby="travelPlans">
        <thead>
          <tr>
            <th scope="row"><span v-text="$t('global.field.id')">ID</span></th>
            <th scope="row"><span v-text="$t('travelTutorialCompleteApp.travelPlan.name')">Name</span></th>
            <th scope="row"><span v-text="$t('travelTutorialCompleteApp.travelPlan.startDate')">Start Date</span></th>
            <th scope="row"><span v-text="$t('travelTutorialCompleteApp.travelPlan.endDate')">End Date</span></th>
            <th scope="row"><span v-text="$t('travelTutorialCompleteApp.travelPlan.numPax')">Num Pax</span></th>
            <th scope="row"><span v-text="$t('travelTutorialCompleteApp.travelPlan.price')">Price</span></th>
            <th scope="row"><span v-text="$t('travelTutorialCompleteApp.travelPlan.payment')">Payment</span></th>
            <th scope="row"><span v-text="$t('travelTutorialCompleteApp.travelPlan.hotelDuration')">Hotel Duration</span></th>
            <th scope="row"><span v-text="$t('travelTutorialCompleteApp.travelPlan.carDuration')">Car Duration</span></th>
            <th scope="row"><span v-text="$t('travelTutorialCompleteApp.travelPlan.status')">Status</span></th>
            <th scope="row"><span v-text="$t('travelTutorialCompleteApp.travelPlan.car')">Car</span></th>
            <th scope="row"><span v-text="$t('travelTutorialCompleteApp.travelPlan.flight')">Flight</span></th>
            <th scope="row"><span v-text="$t('travelTutorialCompleteApp.travelPlan.hotelRoom')">Hotel Room</span></th>
            <th scope="row"></th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="travelPlan in travelPlans" :key="travelPlan.id" data-cy="entityTable">
            <td>
              <router-link :to="{ name: 'TravelPlanView', params: { travelPlanId: travelPlan.id } }">{{ travelPlan.id }}</router-link>
            </td>
            <td>{{ travelPlan.name }}</td>
            <td>{{ travelPlan.startDate }}</td>
            <td>{{ travelPlan.endDate }}</td>
            <td>{{ travelPlan.numPax }}</td>
            <td>{{ travelPlan.price }}</td>
            <td>{{ travelPlan.payment }}</td>
            <td>{{ travelPlan.hotelDuration }}</td>
            <td>{{ travelPlan.carDuration }}</td>
            <td v-text="$t('travelTutorialCompleteApp.PlanStatus.' + travelPlan.status)">{{ travelPlan.status }}</td>
            <td>
              <div v-if="travelPlan.car">
                <router-link :to="{ name: 'CarView', params: { carId: travelPlan.car.id } }">{{ travelPlan.car.code }}</router-link>
              </div>
            </td>
            <td>
              <div v-if="travelPlan.flight">
                <router-link :to="{ name: 'FlightView', params: { flightId: travelPlan.flight.id } }">{{
                  travelPlan.flight.code
                }}</router-link>
              </div>
            </td>
            <td>
              <div v-if="travelPlan.hotelRoom">
                <router-link :to="{ name: 'HotelRoomView', params: { hotelRoomId: travelPlan.hotelRoom.id } }">{{
                  travelPlan.hotelRoom.code
                }}</router-link>
              </div>
            </td>
            <td class="text-right">
              <div class="btn-group">
                <router-link :to="{ name: 'TravelPlanView', params: { travelPlanId: travelPlan.id } }" custom v-slot="{ navigate }">
                  <button @click="navigate" class="btn btn-info btn-sm details" data-cy="entityDetailsButton">
                    <font-awesome-icon icon="eye"></font-awesome-icon>
                    <span class="d-none d-md-inline" v-text="$t('entity.action.view')">View</span>
                  </button>
                </router-link>
              </div>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
    <b-modal ref="removeEntity" id="removeEntity">
      <span slot="modal-title"
        ><span
          id="travelTutorialCompleteApp.travelPlan.delete.question"
          data-cy="travelPlanDeleteDialogHeading"
          v-text="$t('entity.delete.title')"
          >Confirm delete operation</span
        ></span
      >
      <div class="modal-body">
        <p id="jhi-delete-travelPlan-heading" v-text="$t('travelTutorialCompleteApp.travelPlan.delete.question', { id: removeId })">
          Are you sure you want to delete this Travel Plan?
        </p>
      </div>
      <div slot="modal-footer">
        <button type="button" class="btn btn-secondary" v-text="$t('entity.action.cancel')" v-on:click="closeDialog()">Cancel</button>
        <button
          type="button"
          class="btn btn-primary"
          id="jhi-confirm-delete-travelPlan"
          data-cy="entityConfirmDeleteButton"
          v-text="$t('entity.action.delete')"
          v-on:click="removeTravelPlan()"
        >
          Delete
        </button>
      </div>
    </b-modal>
  </div>
</template>

<script lang="ts" src="./travel-plan.component.ts"></script>

// XXX/src/main/webapp/app/entities/travel-plan/list/travel-plan.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { ITravelPlan } from '../travel-plan.model';
import { TravelPlanService } from '../service/travel-plan.service';
import { TravelPlanDeleteDialogComponent } from '../delete/travel-plan-delete-dialog.component';

@Component({
  selector: 'jhi-travel-plan',
  templateUrl: './travel-plan.component.html',
})
export class TravelPlanComponent implements OnInit {
  travelPlans?: ITravelPlan[];
  isLoading = false;

  constructor(protected travelPlanService: TravelPlanService, protected modalService: NgbModal) {}

  loadAll(): void {
    this.isLoading = true;

    this.travelPlanService.query().subscribe(
      (res: HttpResponse<ITravelPlan[]>) => {
        this.isLoading = false;
        this.travelPlans = res.body ?? [];
      },
      () => {
        this.isLoading = false;
      }
    );
  }

  ngOnInit(): void {
    this.loadAll();
  }

  trackId(index: number, item: ITravelPlan): number {
    return item.id!;
  }

  delete(travelPlan: ITravelPlan): void {
    const modalRef = this.modalService.open(TravelPlanDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.travelPlan = travelPlan;
    // unsubscribe not needed because closed completes on modal close
    modalRef.closed.subscribe(reason => {
      if (reason === 'deleted') {
        this.loadAll();
      }
    });
  }
}

<div>
  <h2 id="page-heading" data-cy="TravelPlanHeading">
    <span jhiTranslate="travelTutorialCompleteApp.travelPlan.home.title">Travel Plans</span>

    <div class="d-flex justify-content-end">
      <button class="btn btn-info mr-2" (click)="loadAll()" [disabled]="isLoading">
        <fa-icon icon="sync" [spin]="isLoading"></fa-icon>
        <span jhiTranslate="travelTutorialCompleteApp.travelPlan.home.refreshListLabel">Refresh List</span>
      </button>

      <button
        id="jh-create-entity"
        data-cy="entityCreateButton"
        class="btn btn-primary jh-create-entity create-travel-plan"
        [routerLink]="['/travel-plan/new']"
      >
        <fa-icon icon="plus"></fa-icon>
        <span jhiTranslate="travelTutorialCompleteApp.travelPlan.home.createLabel"> Create a new Travel Plan </span>
      </button>
    </div>
  </h2>

  <jhi-alert-error></jhi-alert-error>

  <jhi-alert></jhi-alert>

  <div class="alert alert-warning" id="no-result" *ngIf="travelPlans?.length === 0">
    <span jhiTranslate="travelTutorialCompleteApp.travelPlan.home.notFound">No travelPlans found</span>
  </div>

  <div class="table-responsive" id="entities" *ngIf="travelPlans && travelPlans.length > 0">
    <table class="table table-striped" aria-describedby="page-heading">
      <thead>
        <tr>
          <th scope="col"><span jhiTranslate="global.field.id">ID</span></th>
          <th scope="col"><span jhiTranslate="travelTutorialCompleteApp.travelPlan.name">Name</span></th>
          <th scope="col"><span jhiTranslate="travelTutorialCompleteApp.travelPlan.startDate">Start Date</span></th>
          <th scope="col"><span jhiTranslate="travelTutorialCompleteApp.travelPlan.endDate">End Date</span></th>
          <th scope="col"><span jhiTranslate="travelTutorialCompleteApp.travelPlan.numPax">Num Pax</span></th>
          <th scope="col"><span jhiTranslate="travelTutorialCompleteApp.travelPlan.price">Price</span></th>
          <th scope="col"><span jhiTranslate="travelTutorialCompleteApp.travelPlan.payment">Payment</span></th>
          <th scope="col"><span jhiTranslate="travelTutorialCompleteApp.travelPlan.hotelDuration">Hotel Duration</span></th>
          <th scope="col"><span jhiTranslate="travelTutorialCompleteApp.travelPlan.carDuration">Car Duration</span></th>
          <th scope="col"><span jhiTranslate="travelTutorialCompleteApp.travelPlan.status">Status</span></th>
          <th scope="col"><span jhiTranslate="travelTutorialCompleteApp.travelPlan.car">Car</span></th>
          <th scope="col"><span jhiTranslate="travelTutorialCompleteApp.travelPlan.flight">Flight</span></th>
          <th scope="col"><span jhiTranslate="travelTutorialCompleteApp.travelPlan.hotelRoom">Hotel Room</span></th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let travelPlan of travelPlans; trackBy: trackId" data-cy="entityTable">
          <td>
            <a [routerLink]="['/travel-plan', travelPlan.id, 'view']">{{ travelPlan.id }}</a>
          </td>
          <td>{{ travelPlan.name }}</td>
          <td>{{ travelPlan.startDate | formatMediumDate }}</td>
          <td>{{ travelPlan.endDate | formatMediumDate }}</td>
          <td>{{ travelPlan.numPax }}</td>
          <td>{{ travelPlan.price }}</td>
          <td>{{ travelPlan.payment }}</td>
          <td>{{ travelPlan.hotelDuration }}</td>
          <td>{{ travelPlan.carDuration }}</td>
          <td jhiTranslate="{{ 'travelTutorialCompleteApp.PlanStatus.' + travelPlan.status }}">{{ travelPlan.status }}</td>
          <td>
            <div *ngIf="travelPlan.car">
              <a [routerLink]="['/car', travelPlan.car?.id, 'view']">{{ travelPlan.car?.code }}</a>
            </div>
          </td>
          <td>
            <div *ngIf="travelPlan.flight">
              <a [routerLink]="['/flight', travelPlan.flight?.id, 'view']">{{ travelPlan.flight?.code }}</a>
            </div>
          </td>
          <td>
            <div *ngIf="travelPlan.hotelRoom">
              <a [routerLink]="['/hotel-room', travelPlan.hotelRoom?.id, 'view']">{{ travelPlan.hotelRoom?.code }}</a>
            </div>
          </td>
          <td class="text-right">
            <div class="btn-group">
              <button
                type="submit"
                [routerLink]="['/travel-plan', travelPlan.id, 'view']"
                class="btn btn-info btn-sm"
                data-cy="entityDetailsButton"
              >
                <fa-icon icon="eye"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
              </button>

              <button
                type="submit"
                [routerLink]="['/travel-plan', travelPlan.id, 'edit']"
                class="btn btn-primary btn-sm"
                data-cy="entityEditButton"
              >
                <fa-icon icon="pencil-alt"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
              </button>

              <button type="submit" (click)="delete(travelPlan)" class="btn btn-danger btn-sm" data-cy="entityDeleteButton">
                <fa-icon icon="times"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
              </button>
            </div>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
