// XXX/src/main/webapp/app/entities/hotel-company/list/hotel-company.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { IHotelCompany } from '../hotel-company.model';
import { HotelCompanyService } from '../service/hotel-company.service';
import { HotelCompanyDeleteDialogComponent } from '../delete/hotel-company-delete-dialog.component';

@Component({
  selector: 'jhi-hotel-company',
  templateUrl: './hotel-company.component.html',
})
export class HotelCompanyComponent implements OnInit {
  hotelCompanies?: IHotelCompany[];
  isLoading = false;

  constructor(protected hotelCompanyService: HotelCompanyService, protected modalService: NgbModal) {}

  loadAll(): void {
    this.isLoading = true;

    this.hotelCompanyService.query().subscribe(
      (res: HttpResponse<IHotelCompany[]>) => {
        this.isLoading = false;
        this.hotelCompanies = res.body ?? [];
      },
      () => {
        this.isLoading = false;
      }
    );
  }

  ngOnInit(): void {
    this.loadAll();
  }

  trackId(index: number, item: IHotelCompany): number {
    return item.id!;
  }

  delete(hotelCompany: IHotelCompany): void {
    const modalRef = this.modalService.open(HotelCompanyDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.hotelCompany = hotelCompany;
    // unsubscribe not needed because closed completes on modal close
    modalRef.closed.subscribe(reason => {
      if (reason === 'deleted') {
        this.loadAll();
      }
    });
  }
}

<div>
  <h2 id="page-heading" data-cy="HotelCompanyHeading">
    <span jhiTranslate="travelTutorialCompleteApp.hotelCompany.home.title">Hotel Companies</span>

    <div class="d-flex justify-content-end">
      <button class="btn btn-info mr-2" (click)="loadAll()" [disabled]="isLoading">
        <fa-icon icon="sync" [spin]="isLoading"></fa-icon>
        <span jhiTranslate="travelTutorialCompleteApp.hotelCompany.home.refreshListLabel">Refresh List</span>
      </button>

      <button
        id="jh-create-entity"
        data-cy="entityCreateButton"
        class="btn btn-primary jh-create-entity create-hotel-company"
        [routerLink]="['/hotel-company/new']"
      >
        <fa-icon icon="plus"></fa-icon>
        <span jhiTranslate="travelTutorialCompleteApp.hotelCompany.home.createLabel"> Create a new Hotel Company </span>
      </button>
    </div>
  </h2>

  <jhi-alert-error></jhi-alert-error>

  <jhi-alert></jhi-alert>

  <div class="alert alert-warning" id="no-result" *ngIf="hotelCompanies?.length === 0">
    <span jhiTranslate="travelTutorialCompleteApp.hotelCompany.home.notFound">No hotelCompanies found</span>
  </div>

  <div class="table-responsive" id="entities" *ngIf="hotelCompanies && hotelCompanies.length > 0">
    <table class="table table-striped" aria-describedby="page-heading">
      <thead>
        <tr>
          <th scope="col"><span jhiTranslate="global.field.id">ID</span></th>
          <th scope="col"><span jhiTranslate="travelTutorialCompleteApp.hotelCompany.name">Name</span></th>
          <th scope="col"><span jhiTranslate="travelTutorialCompleteApp.hotelCompany.place">Place</span></th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let hotelCompany of hotelCompanies; trackBy: trackId" data-cy="entityTable">
          <td>
            <a [routerLink]="['/hotel-company', hotelCompany.id, 'view']">{{ hotelCompany.id }}</a>
          </td>
          <td>{{ hotelCompany.name }}</td>
          <td>{{ hotelCompany.place }}</td>
          <td class="text-right">
            <div class="btn-group">
              <button
                type="submit"
                [routerLink]="['/hotel-company', hotelCompany.id, 'view']"
                class="btn btn-info btn-sm"
                data-cy="entityDetailsButton"
              >
                <fa-icon icon="eye"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
              </button>

              <button
                type="submit"
                [routerLink]="['/hotel-company', hotelCompany.id, 'edit']"
                class="btn btn-primary btn-sm"
                data-cy="entityEditButton"
              >
                <fa-icon icon="pencil-alt"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
              </button>

              <button type="submit" (click)="delete(hotelCompany)" class="btn btn-danger btn-sm" data-cy="entityDeleteButton">
                <fa-icon icon="times"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
              </button>
            </div>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

// travelTutorialCOMPLETE/src/main/webapp/app/entities/hotel-company/hotel-company.vue
<template>
  <div>
    <h2 id="page-heading" data-cy="HotelCompanyHeading">
      <span v-text="$t('travelTutorialCompleteApp.hotelCompany.home.title')" id="hotel-company-heading">Hotel Companies</span>
      <div class="d-flex justify-content-end">
        <button class="btn btn-info mr-2" v-on:click="handleSyncList" :disabled="isFetching">
          <font-awesome-icon icon="sync" :spin="isFetching"></font-awesome-icon>
          <span v-text="$t('travelTutorialCompleteApp.hotelCompany.home.refreshListLabel')">Refresh List</span>
        </button>
        <router-link :to="{ name: 'HotelCompanyCreate' }" custom v-slot="{ navigate }">
          <button
            @click="navigate"
            id="jh-create-entity"
            data-cy="entityCreateButton"
            class="btn btn-primary jh-create-entity create-hotel-company"
          >
            <font-awesome-icon icon="plus"></font-awesome-icon>
            <span v-text="$t('travelTutorialCompleteApp.hotelCompany.home.createLabel')"> Create a new Hotel Company </span>
          </button>
        </router-link>
      </div>
    </h2>
    <br />
    <div class="alert alert-warning" v-if="!isFetching && hotelCompanies && hotelCompanies.length === 0">
      <span v-text="$t('travelTutorialCompleteApp.hotelCompany.home.notFound')">No hotelCompanies found</span>
    </div>
    <div class="table-responsive" v-if="hotelCompanies && hotelCompanies.length > 0">
      <table class="table table-striped" aria-describedby="hotelCompanies">
        <thead>
          <tr>
            <th scope="row"><span v-text="$t('global.field.id')">ID</span></th>
            <th scope="row"><span v-text="$t('travelTutorialCompleteApp.hotelCompany.name')">Name</span></th>
            <th scope="row"><span v-text="$t('travelTutorialCompleteApp.hotelCompany.place')">Place</span></th>
            <th scope="row"></th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="hotelCompany in hotelCompanies" :key="hotelCompany.id" data-cy="entityTable">
            <td>
              <router-link :to="{ name: 'HotelCompanyView', params: { hotelCompanyId: hotelCompany.id } }">{{
                hotelCompany.id
              }}</router-link>
            </td>
            <td>{{ hotelCompany.name }}</td>
            <td>{{ hotelCompany.place }}</td>
            <td class="text-right">
              <div class="btn-group">
                <router-link :to="{ name: 'HotelCompanyView', params: { hotelCompanyId: hotelCompany.id } }" custom v-slot="{ navigate }">
                  <button @click="navigate" class="btn btn-info btn-sm details" data-cy="entityDetailsButton">
                    <font-awesome-icon icon="eye"></font-awesome-icon>
                    <span class="d-none d-md-inline" v-text="$t('entity.action.view')">View</span>
                  </button>
                </router-link>
                <router-link :to="{ name: 'HotelCompanyEdit', params: { hotelCompanyId: hotelCompany.id } }" custom v-slot="{ navigate }">
                  <button @click="navigate" class="btn btn-primary btn-sm edit" data-cy="entityEditButton">
                    <font-awesome-icon icon="pencil-alt"></font-awesome-icon>
                    <span class="d-none d-md-inline" v-text="$t('entity.action.edit')">Edit</span>
                  </button>
                </router-link>
                <b-button
                  v-on:click="prepareRemove(hotelCompany)"
                  variant="danger"
                  class="btn btn-sm"
                  data-cy="entityDeleteButton"
                  v-b-modal.removeEntity
                >
                  <font-awesome-icon icon="times"></font-awesome-icon>
                  <span class="d-none d-md-inline" v-text="$t('entity.action.delete')">Delete</span>
                </b-button>
              </div>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
    <b-modal ref="removeEntity" id="removeEntity">
      <span slot="modal-title"
        ><span
          id="travelTutorialCompleteApp.hotelCompany.delete.question"
          data-cy="hotelCompanyDeleteDialogHeading"
          v-text="$t('entity.delete.title')"
          >Confirm delete operation</span
        ></span
      >
      <div class="modal-body">
        <p id="jhi-delete-hotelCompany-heading" v-text="$t('travelTutorialCompleteApp.hotelCompany.delete.question', { id: removeId })">
          Are you sure you want to delete this Hotel Company?
        </p>
      </div>
      <div slot="modal-footer">
        <button type="button" class="btn btn-secondary" v-text="$t('entity.action.cancel')" v-on:click="closeDialog()">Cancel</button>
        <button
          type="button"
          class="btn btn-primary"
          id="jhi-confirm-delete-hotelCompany"
          data-cy="entityConfirmDeleteButton"
          v-text="$t('entity.action.delete')"
          v-on:click="removeHotelCompany()"
        >
          Delete
        </button>
      </div>
    </b-modal>
  </div>
</template>

<script lang="ts" src="./hotel-company.component.ts"></script>
