// travelTutorialCOMPLETE/src/main/webapp/app/entities/airline-company/airline-company.vue
<template>
  <div>
    <h2 id="page-heading" data-cy="AirlineCompanyHeading">
      <span v-text="$t('travelTutorialCompleteApp.airlineCompany.home.title')" id="airline-company-heading">Airline Companies</span>
      <div class="d-flex justify-content-end">
        <button class="btn btn-info mr-2" v-on:click="handleSyncList" :disabled="isFetching">
          <font-awesome-icon icon="sync" :spin="isFetching"></font-awesome-icon>
          <span v-text="$t('travelTutorialCompleteApp.airlineCompany.home.refreshListLabel')">Refresh List</span>
        </button>
        <router-link :to="{ name: 'AirlineCompanyCreate' }" custom v-slot="{ navigate }">
          <button
            @click="navigate"
            id="jh-create-entity"
            data-cy="entityCreateButton"
            class="btn btn-primary jh-create-entity create-airline-company"
          >
            <font-awesome-icon icon="plus"></font-awesome-icon>
            <span v-text="$t('travelTutorialCompleteApp.airlineCompany.home.createLabel')"> Create a new Airline Company </span>
          </button>
        </router-link>
      </div>
    </h2>
    <br />
    <div class="alert alert-warning" v-if="!isFetching && airlineCompanies && airlineCompanies.length === 0">
      <span v-text="$t('travelTutorialCompleteApp.airlineCompany.home.notFound')">No airlineCompanies found</span>
    </div>
    <div class="table-responsive" v-if="airlineCompanies && airlineCompanies.length > 0">
      <table class="table table-striped" aria-describedby="airlineCompanies">
        <thead>
          <tr>
            <th scope="row"><span v-text="$t('global.field.id')">ID</span></th>
            <th scope="row"><span v-text="$t('travelTutorialCompleteApp.airlineCompany.name')">Name</span></th>
            <th scope="row"><span v-text="$t('travelTutorialCompleteApp.airlineCompany.code')">Code</span></th>
            <th scope="row"></th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="airlineCompany in airlineCompanies" :key="airlineCompany.id" data-cy="entityTable">
            <td>
              <router-link :to="{ name: 'AirlineCompanyView', params: { airlineCompanyId: airlineCompany.id } }">{{
                airlineCompany.id
              }}</router-link>
            </td>
            <td>{{ airlineCompany.name }}</td>
            <td>{{ airlineCompany.code }}</td>
            <td class="text-right">
              <div class="btn-group">
                <router-link
                  :to="{ name: 'AirlineCompanyView', params: { airlineCompanyId: airlineCompany.id } }"
                  custom
                  v-slot="{ navigate }"
                >
                  <button @click="navigate" class="btn btn-info btn-sm details" data-cy="entityDetailsButton">
                    <font-awesome-icon icon="eye"></font-awesome-icon>
                    <span class="d-none d-md-inline" v-text="$t('entity.action.view')">View</span>
                  </button>
                </router-link>
                <router-link
                  :to="{ name: 'AirlineCompanyEdit', params: { airlineCompanyId: airlineCompany.id } }"
                  custom
                  v-slot="{ navigate }"
                >
                  <button @click="navigate" class="btn btn-primary btn-sm edit" data-cy="entityEditButton">
                    <font-awesome-icon icon="pencil-alt"></font-awesome-icon>
                    <span class="d-none d-md-inline" v-text="$t('entity.action.edit')">Edit</span>
                  </button>
                </router-link>
                <b-button
                  v-on:click="prepareRemove(airlineCompany)"
                  variant="danger"
                  class="btn btn-sm"
                  data-cy="entityDeleteButton"
                  v-b-modal.removeEntity
                >
                  <font-awesome-icon icon="times"></font-awesome-icon>
                  <span class="d-none d-md-inline" v-text="$t('entity.action.delete')">Delete</span>
                </b-button>
              </div>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
    <b-modal ref="removeEntity" id="removeEntity">
      <span slot="modal-title"
        ><span
          id="travelTutorialCompleteApp.airlineCompany.delete.question"
          data-cy="airlineCompanyDeleteDialogHeading"
          v-text="$t('entity.delete.title')"
          >Confirm delete operation</span
        ></span
      >
      <div class="modal-body">
        <p id="jhi-delete-airlineCompany-heading" v-text="$t('travelTutorialCompleteApp.airlineCompany.delete.question', { id: removeId })">
          Are you sure you want to delete this Airline Company?
        </p>
      </div>
      <div slot="modal-footer">
        <button type="button" class="btn btn-secondary" v-text="$t('entity.action.cancel')" v-on:click="closeDialog()">Cancel</button>
        <button
          type="button"
          class="btn btn-primary"
          id="jhi-confirm-delete-airlineCompany"
          data-cy="entityConfirmDeleteButton"
          v-text="$t('entity.action.delete')"
          v-on:click="removeAirlineCompany()"
        >
          Delete
        </button>
      </div>
    </b-modal>
  </div>
</template>

<script lang="ts" src="./airline-company.component.ts"></script>

// XXX/src/main/webapp/app/entities/airline-company/list/airline-company.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { IAirlineCompany } from '../airline-company.model';
import { AirlineCompanyService } from '../service/airline-company.service';
import { AirlineCompanyDeleteDialogComponent } from '../delete/airline-company-delete-dialog.component';

@Component({
  selector: 'jhi-airline-company',
  templateUrl: './airline-company.component.html',
})
export class AirlineCompanyComponent implements OnInit {
  airlineCompanies?: IAirlineCompany[];
  isLoading = false;

  constructor(protected airlineCompanyService: AirlineCompanyService, protected modalService: NgbModal) {}

  loadAll(): void {
    this.isLoading = true;

    this.airlineCompanyService.query().subscribe(
      (res: HttpResponse<IAirlineCompany[]>) => {
        this.isLoading = false;
        this.airlineCompanies = res.body ?? [];
      },
      () => {
        this.isLoading = false;
      }
    );
  }

  ngOnInit(): void {
    this.loadAll();
  }

  trackId(index: number, item: IAirlineCompany): number {
    return item.id!;
  }

  delete(airlineCompany: IAirlineCompany): void {
    const modalRef = this.modalService.open(AirlineCompanyDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.airlineCompany = airlineCompany;
    // unsubscribe not needed because closed completes on modal close
    modalRef.closed.subscribe(reason => {
      if (reason === 'deleted') {
        this.loadAll();
      }
    });
  }
}

<div>
  <h2 id="page-heading" data-cy="AirlineCompanyHeading">
    <span jhiTranslate="travelTutorialCompleteApp.airlineCompany.home.title">Airline Companies</span>

    <div class="d-flex justify-content-end">
      <button class="btn btn-info mr-2" (click)="loadAll()" [disabled]="isLoading">
        <fa-icon icon="sync" [spin]="isLoading"></fa-icon>
        <span jhiTranslate="travelTutorialCompleteApp.airlineCompany.home.refreshListLabel">Refresh List</span>
      </button>

      <button
        id="jh-create-entity"
        data-cy="entityCreateButton"
        class="btn btn-primary jh-create-entity create-airline-company"
        [routerLink]="['/airline-company/new']"
      >
        <fa-icon icon="plus"></fa-icon>
        <span jhiTranslate="travelTutorialCompleteApp.airlineCompany.home.createLabel"> Create a new Airline Company </span>
      </button>
    </div>
  </h2>

  <jhi-alert-error></jhi-alert-error>

  <jhi-alert></jhi-alert>

  <div class="alert alert-warning" id="no-result" *ngIf="airlineCompanies?.length === 0">
    <span jhiTranslate="travelTutorialCompleteApp.airlineCompany.home.notFound">No airlineCompanies found</span>
  </div>

  <div class="table-responsive" id="entities" *ngIf="airlineCompanies && airlineCompanies.length > 0">
    <table class="table table-striped" aria-describedby="page-heading">
      <thead>
        <tr>
          <th scope="col"><span jhiTranslate="global.field.id">ID</span></th>
          <th scope="col"><span jhiTranslate="travelTutorialCompleteApp.airlineCompany.name">Name</span></th>
          <th scope="col"><span jhiTranslate="travelTutorialCompleteApp.airlineCompany.code">Code</span></th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let airlineCompany of airlineCompanies; trackBy: trackId" data-cy="entityTable">
          <td>
            <a [routerLink]="['/airline-company', airlineCompany.id, 'view']">{{ airlineCompany.id }}</a>
          </td>
          <td>{{ airlineCompany.name }}</td>
          <td>{{ airlineCompany.code }}</td>
          <td class="text-right">
            <div class="btn-group">
              <button
                type="submit"
                [routerLink]="['/airline-company', airlineCompany.id, 'view']"
                class="btn btn-info btn-sm"
                data-cy="entityDetailsButton"
              >
                <fa-icon icon="eye"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
              </button>

              <button
                type="submit"
                [routerLink]="['/airline-company', airlineCompany.id, 'edit']"
                class="btn btn-primary btn-sm"
                data-cy="entityEditButton"
              >
                <fa-icon icon="pencil-alt"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
              </button>

              <button type="submit" (click)="delete(airlineCompany)" class="btn btn-danger btn-sm" data-cy="entityDeleteButton">
                <fa-icon icon="times"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
              </button>
            </div>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
