// travelTutorialCOMPLETE/src/main/webapp/app/entities/airline-company/airline-company-update.vue
<template>
  <div class="row justify-content-center">
    <div class="col-8">
      <form name="editForm" role="form" novalidate v-on:submit.prevent="save()">
        <h2
          id="travelTutorialCompleteApp.airlineCompany.home.createOrEditLabel"
          data-cy="AirlineCompanyCreateUpdateHeading"
          v-text="$t('travelTutorialCompleteApp.airlineCompany.home.createOrEditLabel')"
        >
          Create or edit a AirlineCompany
        </h2>
        <div>
          <div class="form-group" v-if="airlineCompany.id">
            <label for="id" v-text="$t('global.field.id')">ID</label>
            <input type="text" class="form-control" id="id" name="id" v-model="airlineCompany.id" readonly />
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('travelTutorialCompleteApp.airlineCompany.name')" for="airline-company-name"
              >Name</label
            >
            <input
              type="text"
              class="form-control"
              name="name"
              id="airline-company-name"
              data-cy="name"
              :class="{ valid: !$v.airlineCompany.name.$invalid, invalid: $v.airlineCompany.name.$invalid }"
              v-model="$v.airlineCompany.name.$model"
              required
            />
            <div v-if="$v.airlineCompany.name.$anyDirty && $v.airlineCompany.name.$invalid">
              <small class="form-text text-danger" v-if="!$v.airlineCompany.name.required" v-text="$t('entity.validation.required')">
                This field is required.
              </small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('travelTutorialCompleteApp.airlineCompany.code')" for="airline-company-code"
              >Code</label
            >
            <input
              type="text"
              class="form-control"
              name="code"
              id="airline-company-code"
              data-cy="code"
              :class="{ valid: !$v.airlineCompany.code.$invalid, invalid: $v.airlineCompany.code.$invalid }"
              v-model="$v.airlineCompany.code.$model"
              required
            />
            <div v-if="$v.airlineCompany.code.$anyDirty && $v.airlineCompany.code.$invalid">
              <small class="form-text text-danger" v-if="!$v.airlineCompany.code.required" v-text="$t('entity.validation.required')">
                This field is required.
              </small>
              <small
                class="form-text text-danger"
                v-if="!$v.airlineCompany.code.minLength"
                v-text="$t('entity.validation.minlength', { min: 3 })"
              >
                This field is required to be at least 3 characters.
              </small>
              <small
                class="form-text text-danger"
                v-if="!$v.airlineCompany.code.maxLength"
                v-text="$t('entity.validation.maxlength', { max: 3 })"
              >
                This field cannot be longer than 3 characters.
              </small>
            </div>
          </div>
        </div>
        <div>
          <button type="button" id="cancel-save" class="btn btn-secondary" v-on:click="previousState()">
            <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.cancel')">Cancel</span>
          </button>
          <button
            type="submit"
            id="save-entity"
            data-cy="entityCreateSaveButton"
            :disabled="$v.airlineCompany.$invalid || isSaving"
            class="btn btn-primary"
          >
            <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.save')">Save</span>
          </button>
        </div>
      </form>
    </div>
  </div>
</template>
<script lang="ts" src="./airline-company-update.component.ts"></script>

// XXX/src/main/webapp/app/entities/airline-company/update/airline-company-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { finalize } from 'rxjs/operators';

import { IAirlineCompany, AirlineCompany } from '../airline-company.model';
import { AirlineCompanyService } from '../service/airline-company.service';

@Component({
  selector: 'jhi-airline-company-update',
  templateUrl: './airline-company-update.component.html',
})
export class AirlineCompanyUpdateComponent implements OnInit {
  isSaving = false;

  editForm = this.fb.group({
    id: [],
    name: [null, [Validators.required]],
    code: [null, [Validators.required, Validators.minLength(3), Validators.maxLength(3)]],
  });

  constructor(
    protected airlineCompanyService: AirlineCompanyService,
    protected activatedRoute: ActivatedRoute,
    protected fb: FormBuilder
  ) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ airlineCompany }) => {
      this.updateForm(airlineCompany);
    });
  }

  previousState(): void {
    window.history.back();
  }

  save(): void {
    this.isSaving = true;
    const airlineCompany = this.createFromForm();
    if (airlineCompany.id !== undefined) {
      this.subscribeToSaveResponse(this.airlineCompanyService.update(airlineCompany));
    } else {
      this.subscribeToSaveResponse(this.airlineCompanyService.create(airlineCompany));
    }
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<IAirlineCompany>>): void {
    result.pipe(finalize(() => this.onSaveFinalize())).subscribe(
      () => this.onSaveSuccess(),
      () => this.onSaveError()
    );
  }

  protected onSaveSuccess(): void {
    this.previousState();
  }

  protected onSaveError(): void {
    // Api for inheritance.
  }

  protected onSaveFinalize(): void {
    this.isSaving = false;
  }

  protected updateForm(airlineCompany: IAirlineCompany): void {
    this.editForm.patchValue({
      id: airlineCompany.id,
      name: airlineCompany.name,
      code: airlineCompany.code,
    });
  }

  protected createFromForm(): IAirlineCompany {
    return {
      ...new AirlineCompany(),
      id: this.editForm.get(['id'])!.value,
      name: this.editForm.get(['name'])!.value,
      code: this.editForm.get(['code'])!.value,
    };
  }
}

<div class="row justify-content-center">
  <div class="col-8">
    <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
      <h2
        id="jhi-airline-company-heading"
        data-cy="AirlineCompanyCreateUpdateHeading"
        jhiTranslate="travelTutorialCompleteApp.airlineCompany.home.createOrEditLabel"
      >
        Create or edit a Airline Company
      </h2>

      <div>
        <jhi-alert-error></jhi-alert-error>

        <div class="form-group" [hidden]="editForm.get('id')!.value == null">
          <label class="form-control-label" jhiTranslate="global.field.id" for="field_id">ID</label>
          <input type="number" class="form-control" name="id" id="field_id" data-cy="id" formControlName="id" [readonly]="true" />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="travelTutorialCompleteApp.airlineCompany.name" for="field_name">Name</label>
          <input type="text" class="form-control" name="name" id="field_name" data-cy="name" formControlName="name" />
          <div *ngIf="editForm.get('name')!.invalid && (editForm.get('name')!.dirty || editForm.get('name')!.touched)">
            <small class="form-text text-danger" *ngIf="editForm.get('name')?.errors?.required" jhiTranslate="entity.validation.required">
              This field is required.
            </small>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="travelTutorialCompleteApp.airlineCompany.code" for="field_code">Code</label>
          <input type="text" class="form-control" name="code" id="field_code" data-cy="code" formControlName="code" />
          <div *ngIf="editForm.get('code')!.invalid && (editForm.get('code')!.dirty || editForm.get('code')!.touched)">
            <small class="form-text text-danger" *ngIf="editForm.get('code')?.errors?.required" jhiTranslate="entity.validation.required">
              This field is required.
            </small>
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('code')?.errors?.minlength"
              jhiTranslate="entity.validation.minlength"
              [translateValues]="{ min: 3 }"
            >
              This field is required to be at least 3 characters.
            </small>
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('code')?.errors?.maxlength"
              jhiTranslate="entity.validation.maxlength"
              [translateValues]="{ max: 3 }"
            >
              This field cannot be longer than 3 characters.
            </small>
          </div>
        </div>
      </div>

      <div>
        <button type="button" id="cancel-save" class="btn btn-secondary" (click)="previousState()">
          <fa-icon icon="ban"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
        </button>

        <button
          type="submit"
          id="save-entity"
          data-cy="entityCreateSaveButton"
          [disabled]="editForm.invalid || isSaving"
          class="btn btn-primary"
        >
          <fa-icon icon="save"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
        </button>
      </div>
    </form>
  </div>
</div>
