// travelTutorialCOMPLETE/src/main/webapp/app/entities/airport/airport.vue
<template>
  <div>
    <h2 id="page-heading" data-cy="AirportHeading">
      <span v-text="$t('travelTutorialCompleteApp.airport.home.title')" id="airport-heading">Airports</span>
      <div class="d-flex justify-content-end">
        <button class="btn btn-info mr-2" v-on:click="handleSyncList" :disabled="isFetching">
          <font-awesome-icon icon="sync" :spin="isFetching"></font-awesome-icon>
          <span v-text="$t('travelTutorialCompleteApp.airport.home.refreshListLabel')">Refresh List</span>
        </button>
        <router-link :to="{ name: 'AirportCreate' }" custom v-slot="{ navigate }">
          <button
            @click="navigate"
            id="jh-create-entity"
            data-cy="entityCreateButton"
            class="btn btn-primary jh-create-entity create-airport"
          >
            <font-awesome-icon icon="plus"></font-awesome-icon>
            <span v-text="$t('travelTutorialCompleteApp.airport.home.createLabel')"> Create a new Airport </span>
          </button>
        </router-link>
      </div>
    </h2>
    <br />
    <div class="alert alert-warning" v-if="!isFetching && airports && airports.length === 0">
      <span v-text="$t('travelTutorialCompleteApp.airport.home.notFound')">No airports found</span>
    </div>
    <div class="table-responsive" v-if="airports && airports.length > 0">
      <table class="table table-striped" aria-describedby="airports">
        <thead>
          <tr>
            <th scope="row"><span v-text="$t('global.field.id')">ID</span></th>
            <th scope="row"><span v-text="$t('travelTutorialCompleteApp.airport.name')">Name</span></th>
            <th scope="row"><span v-text="$t('travelTutorialCompleteApp.airport.city')">City</span></th>
            <th scope="row"><span v-text="$t('travelTutorialCompleteApp.airport.code')">Code</span></th>
            <th scope="row"></th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="airport in airports" :key="airport.id" data-cy="entityTable">
            <td>
              <router-link :to="{ name: 'AirportView', params: { airportId: airport.id } }">{{ airport.id }}</router-link>
            </td>
            <td>{{ airport.name }}</td>
            <td>{{ airport.city }}</td>
            <td>{{ airport.code }}</td>
            <td class="text-right">
              <div class="btn-group">
                <router-link :to="{ name: 'AirportView', params: { airportId: airport.id } }" custom v-slot="{ navigate }">
                  <button @click="navigate" class="btn btn-info btn-sm details" data-cy="entityDetailsButton">
                    <font-awesome-icon icon="eye"></font-awesome-icon>
                    <span class="d-none d-md-inline" v-text="$t('entity.action.view')">View</span>
                  </button>
                </router-link>
                <router-link :to="{ name: 'AirportEdit', params: { airportId: airport.id } }" custom v-slot="{ navigate }">
                  <button @click="navigate" class="btn btn-primary btn-sm edit" data-cy="entityEditButton">
                    <font-awesome-icon icon="pencil-alt"></font-awesome-icon>
                    <span class="d-none d-md-inline" v-text="$t('entity.action.edit')">Edit</span>
                  </button>
                </router-link>
                <b-button
                  v-on:click="prepareRemove(airport)"
                  variant="danger"
                  class="btn btn-sm"
                  data-cy="entityDeleteButton"
                  v-b-modal.removeEntity
                >
                  <font-awesome-icon icon="times"></font-awesome-icon>
                  <span class="d-none d-md-inline" v-text="$t('entity.action.delete')">Delete</span>
                </b-button>
              </div>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
    <b-modal ref="removeEntity" id="removeEntity">
      <span slot="modal-title"
        ><span
          id="travelTutorialCompleteApp.airport.delete.question"
          data-cy="airportDeleteDialogHeading"
          v-text="$t('entity.delete.title')"
          >Confirm delete operation</span
        ></span
      >
      <div class="modal-body">
        <p id="jhi-delete-airport-heading" v-text="$t('travelTutorialCompleteApp.airport.delete.question', { id: removeId })">
          Are you sure you want to delete this Airport?
        </p>
      </div>
      <div slot="modal-footer">
        <button type="button" class="btn btn-secondary" v-text="$t('entity.action.cancel')" v-on:click="closeDialog()">Cancel</button>
        <button
          type="button"
          class="btn btn-primary"
          id="jhi-confirm-delete-airport"
          data-cy="entityConfirmDeleteButton"
          v-text="$t('entity.action.delete')"
          v-on:click="removeAirport()"
        >
          Delete
        </button>
      </div>
    </b-modal>
  </div>
</template>

<script lang="ts" src="./airport.component.ts"></script>

// XXX/src/main/webapp/app/entities/airport/list/airport.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { IAirport } from '../airport.model';
import { AirportService } from '../service/airport.service';
import { AirportDeleteDialogComponent } from '../delete/airport-delete-dialog.component';

@Component({
  selector: 'jhi-airport',
  templateUrl: './airport.component.html',
})
export class AirportComponent implements OnInit {
  airports?: IAirport[];
  isLoading = false;

  constructor(protected airportService: AirportService, protected modalService: NgbModal) {}

  loadAll(): void {
    this.isLoading = true;

    this.airportService.query().subscribe(
      (res: HttpResponse<IAirport[]>) => {
        this.isLoading = false;
        this.airports = res.body ?? [];
      },
      () => {
        this.isLoading = false;
      }
    );
  }

  ngOnInit(): void {
    this.loadAll();
  }

  trackId(index: number, item: IAirport): number {
    return item.id!;
  }

  delete(airport: IAirport): void {
    const modalRef = this.modalService.open(AirportDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.airport = airport;
    // unsubscribe not needed because closed completes on modal close
    modalRef.closed.subscribe(reason => {
      if (reason === 'deleted') {
        this.loadAll();
      }
    });
  }
}

<div>
  <h2 id="page-heading" data-cy="AirportHeading">
    <span jhiTranslate="travelTutorialCompleteApp.airport.home.title">Airports</span>

    <div class="d-flex justify-content-end">
      <button class="btn btn-info mr-2" (click)="loadAll()" [disabled]="isLoading">
        <fa-icon icon="sync" [spin]="isLoading"></fa-icon>
        <span jhiTranslate="travelTutorialCompleteApp.airport.home.refreshListLabel">Refresh List</span>
      </button>

      <button
        id="jh-create-entity"
        data-cy="entityCreateButton"
        class="btn btn-primary jh-create-entity create-airport"
        [routerLink]="['/airport/new']"
      >
        <fa-icon icon="plus"></fa-icon>
        <span jhiTranslate="travelTutorialCompleteApp.airport.home.createLabel"> Create a new Airport </span>
      </button>
    </div>
  </h2>

  <jhi-alert-error></jhi-alert-error>

  <jhi-alert></jhi-alert>

  <div class="alert alert-warning" id="no-result" *ngIf="airports?.length === 0">
    <span jhiTranslate="travelTutorialCompleteApp.airport.home.notFound">No airports found</span>
  </div>

  <div class="table-responsive" id="entities" *ngIf="airports && airports.length > 0">
    <table class="table table-striped" aria-describedby="page-heading">
      <thead>
        <tr>
          <th scope="col"><span jhiTranslate="global.field.id">ID</span></th>
          <th scope="col"><span jhiTranslate="travelTutorialCompleteApp.airport.name">Name</span></th>
          <th scope="col"><span jhiTranslate="travelTutorialCompleteApp.airport.city">City</span></th>
          <th scope="col"><span jhiTranslate="travelTutorialCompleteApp.airport.code">Code</span></th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let airport of airports; trackBy: trackId" data-cy="entityTable">
          <td>
            <a [routerLink]="['/airport', airport.id, 'view']">{{ airport.id }}</a>
          </td>
          <td>{{ airport.name }}</td>
          <td>{{ airport.city }}</td>
          <td>{{ airport.code }}</td>
          <td class="text-right">
            <div class="btn-group">
              <button
                type="submit"
                [routerLink]="['/airport', airport.id, 'view']"
                class="btn btn-info btn-sm"
                data-cy="entityDetailsButton"
              >
                <fa-icon icon="eye"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
              </button>

              <button
                type="submit"
                [routerLink]="['/airport', airport.id, 'edit']"
                class="btn btn-primary btn-sm"
                data-cy="entityEditButton"
              >
                <fa-icon icon="pencil-alt"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
              </button>

              <button type="submit" (click)="delete(airport)" class="btn btn-danger btn-sm" data-cy="entityDeleteButton">
                <fa-icon icon="times"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
              </button>
            </div>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
