// XXX/src/main/webapp/app/entities/airport/update/airport-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { finalize } from 'rxjs/operators';

import { IAirport, Airport } from '../airport.model';
import { AirportService } from '../service/airport.service';

@Component({
  selector: 'jhi-airport-update',
  templateUrl: './airport-update.component.html',
})
export class AirportUpdateComponent implements OnInit {
  isSaving = false;

  editForm = this.fb.group({
    id: [],
    name: [null, [Validators.required]],
    city: [null, [Validators.required]],
    code: [null, [Validators.required, Validators.minLength(3), Validators.maxLength(3)]],
  });

  constructor(protected airportService: AirportService, protected activatedRoute: ActivatedRoute, protected fb: FormBuilder) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ airport }) => {
      this.updateForm(airport);
    });
  }

  previousState(): void {
    window.history.back();
  }

  save(): void {
    this.isSaving = true;
    const airport = this.createFromForm();
    if (airport.id !== undefined) {
      this.subscribeToSaveResponse(this.airportService.update(airport));
    } else {
      this.subscribeToSaveResponse(this.airportService.create(airport));
    }
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<IAirport>>): void {
    result.pipe(finalize(() => this.onSaveFinalize())).subscribe(
      () => this.onSaveSuccess(),
      () => this.onSaveError()
    );
  }

  protected onSaveSuccess(): void {
    this.previousState();
  }

  protected onSaveError(): void {
    // Api for inheritance.
  }

  protected onSaveFinalize(): void {
    this.isSaving = false;
  }

  protected updateForm(airport: IAirport): void {
    this.editForm.patchValue({
      id: airport.id,
      name: airport.name,
      city: airport.city,
      code: airport.code,
    });
  }

  protected createFromForm(): IAirport {
    return {
      ...new Airport(),
      id: this.editForm.get(['id'])!.value,
      name: this.editForm.get(['name'])!.value,
      city: this.editForm.get(['city'])!.value,
      code: this.editForm.get(['code'])!.value,
    };
  }
}

<div class="row justify-content-center">
  <div class="col-8">
    <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
      <h2
        id="jhi-airport-heading"
        data-cy="AirportCreateUpdateHeading"
        jhiTranslate="travelTutorialCompleteApp.airport.home.createOrEditLabel"
      >
        Create or edit a Airport
      </h2>

      <div>
        <jhi-alert-error></jhi-alert-error>

        <div class="form-group" [hidden]="editForm.get('id')!.value == null">
          <label class="form-control-label" jhiTranslate="global.field.id" for="field_id">ID</label>
          <input type="number" class="form-control" name="id" id="field_id" data-cy="id" formControlName="id" [readonly]="true" />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="travelTutorialCompleteApp.airport.name" for="field_name">Name</label>
          <input type="text" class="form-control" name="name" id="field_name" data-cy="name" formControlName="name" />
          <div *ngIf="editForm.get('name')!.invalid && (editForm.get('name')!.dirty || editForm.get('name')!.touched)">
            <small class="form-text text-danger" *ngIf="editForm.get('name')?.errors?.required" jhiTranslate="entity.validation.required">
              This field is required.
            </small>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="travelTutorialCompleteApp.airport.city" for="field_city">City</label>
          <input type="text" class="form-control" name="city" id="field_city" data-cy="city" formControlName="city" />
          <div *ngIf="editForm.get('city')!.invalid && (editForm.get('city')!.dirty || editForm.get('city')!.touched)">
            <small class="form-text text-danger" *ngIf="editForm.get('city')?.errors?.required" jhiTranslate="entity.validation.required">
              This field is required.
            </small>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="travelTutorialCompleteApp.airport.code" for="field_code">Code</label>
          <input type="text" class="form-control" name="code" id="field_code" data-cy="code" formControlName="code" />
          <div *ngIf="editForm.get('code')!.invalid && (editForm.get('code')!.dirty || editForm.get('code')!.touched)">
            <small class="form-text text-danger" *ngIf="editForm.get('code')?.errors?.required" jhiTranslate="entity.validation.required">
              This field is required.
            </small>
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('code')?.errors?.minlength"
              jhiTranslate="entity.validation.minlength"
              [translateValues]="{ min: 3 }"
            >
              This field is required to be at least 3 characters.
            </small>
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('code')?.errors?.maxlength"
              jhiTranslate="entity.validation.maxlength"
              [translateValues]="{ max: 3 }"
            >
              This field cannot be longer than 3 characters.
            </small>
          </div>
        </div>
      </div>

      <div>
        <button type="button" id="cancel-save" class="btn btn-secondary" (click)="previousState()">
          <fa-icon icon="ban"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
        </button>

        <button
          type="submit"
          id="save-entity"
          data-cy="entityCreateSaveButton"
          [disabled]="editForm.invalid || isSaving"
          class="btn btn-primary"
        >
          <fa-icon icon="save"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
        </button>
      </div>
    </form>
  </div>
</div>

// travelTutorialCOMPLETE/src/main/webapp/app/entities/airport/airport-update.vue
<template>
  <div class="row justify-content-center">
    <div class="col-8">
      <form name="editForm" role="form" novalidate v-on:submit.prevent="save()">
        <h2
          id="travelTutorialCompleteApp.airport.home.createOrEditLabel"
          data-cy="AirportCreateUpdateHeading"
          v-text="$t('travelTutorialCompleteApp.airport.home.createOrEditLabel')"
        >
          Create or edit a Airport
        </h2>
        <div>
          <div class="form-group" v-if="airport.id">
            <label for="id" v-text="$t('global.field.id')">ID</label>
            <input type="text" class="form-control" id="id" name="id" v-model="airport.id" readonly />
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('travelTutorialCompleteApp.airport.name')" for="airport-name">Name</label>
            <input
              type="text"
              class="form-control"
              name="name"
              id="airport-name"
              data-cy="name"
              :class="{ valid: !$v.airport.name.$invalid, invalid: $v.airport.name.$invalid }"
              v-model="$v.airport.name.$model"
              required
            />
            <div v-if="$v.airport.name.$anyDirty && $v.airport.name.$invalid">
              <small class="form-text text-danger" v-if="!$v.airport.name.required" v-text="$t('entity.validation.required')">
                This field is required.
              </small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('travelTutorialCompleteApp.airport.city')" for="airport-city">City</label>
            <input
              type="text"
              class="form-control"
              name="city"
              id="airport-city"
              data-cy="city"
              :class="{ valid: !$v.airport.city.$invalid, invalid: $v.airport.city.$invalid }"
              v-model="$v.airport.city.$model"
              required
            />
            <div v-if="$v.airport.city.$anyDirty && $v.airport.city.$invalid">
              <small class="form-text text-danger" v-if="!$v.airport.city.required" v-text="$t('entity.validation.required')">
                This field is required.
              </small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('travelTutorialCompleteApp.airport.code')" for="airport-code">Code</label>
            <input
              type="text"
              class="form-control"
              name="code"
              id="airport-code"
              data-cy="code"
              :class="{ valid: !$v.airport.code.$invalid, invalid: $v.airport.code.$invalid }"
              v-model="$v.airport.code.$model"
              required
            />
            <div v-if="$v.airport.code.$anyDirty && $v.airport.code.$invalid">
              <small class="form-text text-danger" v-if="!$v.airport.code.required" v-text="$t('entity.validation.required')">
                This field is required.
              </small>
              <small class="form-text text-danger" v-if="!$v.airport.code.minLength" v-text="$t('entity.validation.minlength', { min: 3 })">
                This field is required to be at least 3 characters.
              </small>
              <small class="form-text text-danger" v-if="!$v.airport.code.maxLength" v-text="$t('entity.validation.maxlength', { max: 3 })">
                This field cannot be longer than 3 characters.
              </small>
            </div>
          </div>
        </div>
        <div>
          <button type="button" id="cancel-save" class="btn btn-secondary" v-on:click="previousState()">
            <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.cancel')">Cancel</span>
          </button>
          <button
            type="submit"
            id="save-entity"
            data-cy="entityCreateSaveButton"
            :disabled="$v.airport.$invalid || isSaving"
            class="btn btn-primary"
          >
            <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.save')">Save</span>
          </button>
        </div>
      </form>
    </div>
  </div>
</template>
<script lang="ts" src="./airport-update.component.ts"></script>
