// travelTutorialCOMPLETE/src/main/webapp/app/entities/travel-plan/travel-plan-update.vue
<template>
  <div class="row justify-content-center">
    <div class="col-8">
      <form name="editForm" role="form" novalidate v-on:submit.prevent="save()">
        <h2
          id="travelTutorialCompleteApp.travelPlan.home.createOrEditLabel"
          data-cy="TravelPlanCreateUpdateHeading"
          v-text="$t('travelTutorialCompleteApp.travelPlan.home.createOrEditLabel')"
        >
          Create or edit a TravelPlan
        </h2>
        <div>
          <div class="form-group" v-if="travelPlan.id">
            <label for="id" v-text="$t('global.field.id')">ID</label>
            <input type="text" class="form-control" id="id" name="id" v-model="travelPlan.id" readonly />
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('travelTutorialCompleteApp.travelPlan.name')" for="travel-plan-name">Name</label>
            <input
              type="text"
              class="form-control"
              name="name"
              id="travel-plan-name"
              data-cy="name"
              :class="{ valid: !$v.travelPlan.name.$invalid, invalid: $v.travelPlan.name.$invalid }"
              v-model="$v.travelPlan.name.$model"
            />
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('travelTutorialCompleteApp.travelPlan.startDate')" for="travel-plan-startDate"
              >Start Date</label
            >
            <b-input-group class="mb-3">
              <b-input-group-prepend>
                <b-form-datepicker
                  aria-controls="travel-plan-startDate"
                  v-model="$v.travelPlan.startDate.$model"
                  name="startDate"
                  class="form-control"
                  :locale="currentLanguage"
                  button-only
                  today-button
                  reset-button
                  close-button
                >
                </b-form-datepicker>
              </b-input-group-prepend>
              <b-form-input
                id="travel-plan-startDate"
                data-cy="startDate"
                type="text"
                class="form-control"
                name="startDate"
                :class="{ valid: !$v.travelPlan.startDate.$invalid, invalid: $v.travelPlan.startDate.$invalid }"
                v-model="$v.travelPlan.startDate.$model"
              />
            </b-input-group>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('travelTutorialCompleteApp.travelPlan.endDate')" for="travel-plan-endDate"
              >End Date</label
            >
            <b-input-group class="mb-3">
              <b-input-group-prepend>
                <b-form-datepicker
                  aria-controls="travel-plan-endDate"
                  v-model="$v.travelPlan.endDate.$model"
                  name="endDate"
                  class="form-control"
                  :locale="currentLanguage"
                  button-only
                  today-button
                  reset-button
                  close-button
                >
                </b-form-datepicker>
              </b-input-group-prepend>
              <b-form-input
                id="travel-plan-endDate"
                data-cy="endDate"
                type="text"
                class="form-control"
                name="endDate"
                :class="{ valid: !$v.travelPlan.endDate.$invalid, invalid: $v.travelPlan.endDate.$invalid }"
                v-model="$v.travelPlan.endDate.$model"
              />
            </b-input-group>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('travelTutorialCompleteApp.travelPlan.numPax')" for="travel-plan-numPax"
              >Num Pax</label
            >
            <input
              type="number"
              class="form-control"
              name="numPax"
              id="travel-plan-numPax"
              data-cy="numPax"
              :class="{ valid: !$v.travelPlan.numPax.$invalid, invalid: $v.travelPlan.numPax.$invalid }"
              v-model.number="$v.travelPlan.numPax.$model"
            />
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('travelTutorialCompleteApp.travelPlan.price')" for="travel-plan-price"
              >Price</label
            >
            <input
              type="number"
              class="form-control"
              name="price"
              id="travel-plan-price"
              data-cy="price"
              :class="{ valid: !$v.travelPlan.price.$invalid, invalid: $v.travelPlan.price.$invalid }"
              v-model.number="$v.travelPlan.price.$model"
            />
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('travelTutorialCompleteApp.travelPlan.payment')" for="travel-plan-payment"
              >Payment</label
            >
            <input
              type="text"
              class="form-control"
              name="payment"
              id="travel-plan-payment"
              data-cy="payment"
              :class="{ valid: !$v.travelPlan.payment.$invalid, invalid: $v.travelPlan.payment.$invalid }"
              v-model="$v.travelPlan.payment.$model"
            />
          </div>
          <div class="form-group">
            <label
              class="form-control-label"
              v-text="$t('travelTutorialCompleteApp.travelPlan.hotelStartDate')"
              for="travel-plan-hotelStartDate"
              >Hotel Start Date</label
            >
            <b-input-group class="mb-3">
              <b-input-group-prepend>
                <b-form-datepicker
                  aria-controls="travel-plan-hotelStartDate"
                  v-model="$v.travelPlan.hotelStartDate.$model"
                  name="hotelStartDate"
                  class="form-control"
                  :locale="currentLanguage"
                  button-only
                  today-button
                  reset-button
                  close-button
                >
                </b-form-datepicker>
              </b-input-group-prepend>
              <b-form-input
                id="travel-plan-hotelStartDate"
                data-cy="hotelStartDate"
                type="text"
                class="form-control"
                name="hotelStartDate"
                :class="{ valid: !$v.travelPlan.hotelStartDate.$invalid, invalid: $v.travelPlan.hotelStartDate.$invalid }"
                v-model="$v.travelPlan.hotelStartDate.$model"
              />
            </b-input-group>
          </div>
          <div class="form-group">
            <label
              class="form-control-label"
              v-text="$t('travelTutorialCompleteApp.travelPlan.hotelDuration')"
              for="travel-plan-hotelDuration"
              >Hotel Duration</label
            >
            <input
              type="number"
              class="form-control"
              name="hotelDuration"
              id="travel-plan-hotelDuration"
              data-cy="hotelDuration"
              :class="{ valid: !$v.travelPlan.hotelDuration.$invalid, invalid: $v.travelPlan.hotelDuration.$invalid }"
              v-model.number="$v.travelPlan.hotelDuration.$model"
            />
          </div>
          <div class="form-group">
            <label
              class="form-control-label"
              v-text="$t('travelTutorialCompleteApp.travelPlan.carStartDate')"
              for="travel-plan-carStartDate"
              >Car Start Date</label
            >
            <b-input-group class="mb-3">
              <b-input-group-prepend>
                <b-form-datepicker
                  aria-controls="travel-plan-carStartDate"
                  v-model="$v.travelPlan.carStartDate.$model"
                  name="carStartDate"
                  class="form-control"
                  :locale="currentLanguage"
                  button-only
                  today-button
                  reset-button
                  close-button
                >
                </b-form-datepicker>
              </b-input-group-prepend>
              <b-form-input
                id="travel-plan-carStartDate"
                data-cy="carStartDate"
                type="text"
                class="form-control"
                name="carStartDate"
                :class="{ valid: !$v.travelPlan.carStartDate.$invalid, invalid: $v.travelPlan.carStartDate.$invalid }"
                v-model="$v.travelPlan.carStartDate.$model"
              />
            </b-input-group>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('travelTutorialCompleteApp.travelPlan.carDuration')" for="travel-plan-carDuration"
              >Car Duration</label
            >
            <input
              type="number"
              class="form-control"
              name="carDuration"
              id="travel-plan-carDuration"
              data-cy="carDuration"
              :class="{ valid: !$v.travelPlan.carDuration.$invalid, invalid: $v.travelPlan.carDuration.$invalid }"
              v-model.number="$v.travelPlan.carDuration.$model"
            />
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('travelTutorialCompleteApp.travelPlan.status')" for="travel-plan-status"
              >Status</label
            >
            <select
              class="form-control"
              name="status"
              :class="{ valid: !$v.travelPlan.status.$invalid, invalid: $v.travelPlan.status.$invalid }"
              v-model="$v.travelPlan.status.$model"
              id="travel-plan-status"
              data-cy="status"
            >
              <option value="UNKNOWN" v-bind:label="$t('travelTutorialCompleteApp.PlanStatus.UNKNOWN')">UNKNOWN</option>
              <option value="CANCELED" v-bind:label="$t('travelTutorialCompleteApp.PlanStatus.CANCELED')">CANCELED</option>
              <option value="TIMEDOUT" v-bind:label="$t('travelTutorialCompleteApp.PlanStatus.TIMEDOUT')">TIMEDOUT</option>
              <option value="PAID" v-bind:label="$t('travelTutorialCompleteApp.PlanStatus.PAID')">PAID</option>
            </select>
          </div>
          <div class="form-group">
            <label
              class="form-control-label"
              v-text="$t('travelTutorialCompleteApp.travelPlan.proceedToCheckOut')"
              for="travel-plan-proceedToCheckOut"
              >Proceed To Check Out</label
            >
            <input
              type="checkbox"
              class="form-check"
              name="proceedToCheckOut"
              id="travel-plan-proceedToCheckOut"
              data-cy="proceedToCheckOut"
              :class="{ valid: !$v.travelPlan.proceedToCheckOut.$invalid, invalid: $v.travelPlan.proceedToCheckOut.$invalid }"
              v-model="$v.travelPlan.proceedToCheckOut.$model"
            />
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('travelTutorialCompleteApp.travelPlan.car')" for="travel-plan-car">Car</label>
            <select class="form-control" id="travel-plan-car" data-cy="car" name="car" v-model="travelPlan.car">
              <option v-bind:value="null"></option>
              <option
                v-bind:value="travelPlan.car && carOption.id === travelPlan.car.id ? travelPlan.car : carOption"
                v-for="carOption in cars"
                :key="carOption.id"
              >
                {{ carOption.license }}
              </option>
            </select>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('travelTutorialCompleteApp.travelPlan.flight')" for="travel-plan-flight"
              >Flight</label
            >
            <select class="form-control" id="travel-plan-flight" data-cy="flight" name="flight" v-model="travelPlan.flight">
              <option v-bind:value="null"></option>
              <option
                v-bind:value="travelPlan.flight && flightOption.id === travelPlan.flight.id ? travelPlan.flight : flightOption"
                v-for="flightOption in flights"
                :key="flightOption.id"
              >
                {{ flightOption.code }}
              </option>
            </select>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('travelTutorialCompleteApp.travelPlan.hotelRoom')" for="travel-plan-hotelRoom"
              >Hotel Room</label
            >
            <select class="form-control" id="travel-plan-hotelRoom" data-cy="hotelRoom" name="hotelRoom" v-model="travelPlan.hotelRoom">
              <option v-bind:value="null"></option>
              <option
                v-bind:value="
                  travelPlan.hotelRoom && hotelRoomOption.id === travelPlan.hotelRoom.id ? travelPlan.hotelRoom : hotelRoomOption
                "
                v-for="hotelRoomOption in hotelRooms"
                :key="hotelRoomOption.id"
              >
                {{ hotelRoomOption.roomID }}
              </option>
            </select>
          </div>
          <div class="form-group">
            <label v-text="$t('travelTutorialCompleteApp.travelPlan.travelers')" for="travel-plan-travelers">Travelers</label>
            <select
              class="form-control"
              id="travel-plan-travelers"
              data-cy="travelers"
              multiple
              name="travelers"
              v-if="travelPlan.travelers !== undefined"
              v-model="travelPlan.travelers"
            >
              <option
                v-bind:value="getSelected(travelPlan.travelers, travelerOption)"
                v-for="travelerOption in travelers"
                :key="travelerOption.id"
              >
                {{ travelerOption.name }}
              </option>
            </select>
          </div>
        </div>
        <div>
          <button type="button" id="cancel-save" class="btn btn-secondary" v-on:click="previousState()">
            <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.cancel')">Cancel</span>
          </button>
          <button
            type="submit"
            id="save-entity"
            data-cy="entityCreateSaveButton"
            :disabled="$v.travelPlan.$invalid || isSaving"
            class="btn btn-primary"
          >
            <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.save')">Save</span>
          </button>
        </div>
      </form>
    </div>
  </div>
</template>
<script lang="ts" src="./travel-plan-update.component.ts"></script>

// XXX/src/main/webapp/app/entities/travel-plan/update/travel-plan-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { FormBuilder } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { finalize, map } from 'rxjs/operators';

import { ITravelPlan, TravelPlan } from '../travel-plan.model';
import { TravelPlanService } from '../service/travel-plan.service';
import { ICar } from 'app/entities/car/car.model';
import { CarService } from 'app/entities/car/service/car.service';
import { IFlight } from 'app/entities/flight/flight.model';
import { FlightService } from 'app/entities/flight/service/flight.service';
import { IHotelRoom } from 'app/entities/hotel-room/hotel-room.model';
import { HotelRoomService } from 'app/entities/hotel-room/service/hotel-room.service';

@Component({
  selector: 'jhi-travel-plan-update',
  templateUrl: './travel-plan-update.component.html',
})
export class TravelPlanUpdateComponent implements OnInit {
  isSaving = false;

  carsSharedCollection: ICar[] = [];
  flightsSharedCollection: IFlight[] = [];
  hotelRoomsSharedCollection: IHotelRoom[] = [];

  editForm = this.fb.group({
    id: [],
    name: [],
    startDate: [],
    endDate: [],
    numPax: [],
    price: [],
    payment: [],
    hotelDuration: [],
    carDuration: [],
    status: [],
    car: [],
    flight: [],
    hotelRoom: [],
  });

  constructor(
    protected travelPlanService: TravelPlanService,
    protected carService: CarService,
    protected flightService: FlightService,
    protected hotelRoomService: HotelRoomService,
    protected activatedRoute: ActivatedRoute,
    protected fb: FormBuilder
  ) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ travelPlan }) => {
      this.updateForm(travelPlan);

      this.loadRelationshipsOptions();
    });
  }

  previousState(): void {
    window.history.back();
  }

  save(): void {
    this.isSaving = true;
    const travelPlan = this.createFromForm();
    if (travelPlan.id !== undefined) {
      this.subscribeToSaveResponse(this.travelPlanService.update(travelPlan));
    } else {
      this.subscribeToSaveResponse(this.travelPlanService.create(travelPlan));
    }
  }

  trackCarById(index: number, item: ICar): number {
    return item.id!;
  }

  trackFlightById(index: number, item: IFlight): number {
    return item.id!;
  }

  trackHotelRoomById(index: number, item: IHotelRoom): number {
    return item.id!;
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<ITravelPlan>>): void {
    result.pipe(finalize(() => this.onSaveFinalize())).subscribe(
      () => this.onSaveSuccess(),
      () => this.onSaveError()
    );
  }

  protected onSaveSuccess(): void {
    this.previousState();
  }

  protected onSaveError(): void {
    // Api for inheritance.
  }

  protected onSaveFinalize(): void {
    this.isSaving = false;
  }

  protected updateForm(travelPlan: ITravelPlan): void {
    this.editForm.patchValue({
      id: travelPlan.id,
      name: travelPlan.name,
      startDate: travelPlan.startDate,
      endDate: travelPlan.endDate,
      numPax: travelPlan.numPax,
      price: travelPlan.price,
      payment: travelPlan.payment,
      hotelDuration: travelPlan.hotelDuration,
      carDuration: travelPlan.carDuration,
      status: travelPlan.status,
      car: travelPlan.car,
      flight: travelPlan.flight,
      hotelRoom: travelPlan.hotelRoom,
    });

    this.carsSharedCollection = this.carService.addCarToCollectionIfMissing(this.carsSharedCollection, travelPlan.car);
    this.flightsSharedCollection = this.flightService.addFlightToCollectionIfMissing(this.flightsSharedCollection, travelPlan.flight);
    this.hotelRoomsSharedCollection = this.hotelRoomService.addHotelRoomToCollectionIfMissing(
      this.hotelRoomsSharedCollection,
      travelPlan.hotelRoom
    );
  }

  protected loadRelationshipsOptions(): void {
    this.carService
      .query()
      .pipe(map((res: HttpResponse<ICar[]>) => res.body ?? []))
      .pipe(map((cars: ICar[]) => this.carService.addCarToCollectionIfMissing(cars, this.editForm.get('car')!.value)))
      .subscribe((cars: ICar[]) => (this.carsSharedCollection = cars));

    this.flightService
      .query()
      .pipe(map((res: HttpResponse<IFlight[]>) => res.body ?? []))
      .pipe(map((flights: IFlight[]) => this.flightService.addFlightToCollectionIfMissing(flights, this.editForm.get('flight')!.value)))
      .subscribe((flights: IFlight[]) => (this.flightsSharedCollection = flights));

    this.hotelRoomService
      .query()
      .pipe(map((res: HttpResponse<IHotelRoom[]>) => res.body ?? []))
      .pipe(
        map((hotelRooms: IHotelRoom[]) =>
          this.hotelRoomService.addHotelRoomToCollectionIfMissing(hotelRooms, this.editForm.get('hotelRoom')!.value)
        )
      )
      .subscribe((hotelRooms: IHotelRoom[]) => (this.hotelRoomsSharedCollection = hotelRooms));
  }

  protected createFromForm(): ITravelPlan {
    return {
      ...new TravelPlan(),
      id: this.editForm.get(['id'])!.value,
      name: this.editForm.get(['name'])!.value,
      startDate: this.editForm.get(['startDate'])!.value,
      endDate: this.editForm.get(['endDate'])!.value,
      numPax: this.editForm.get(['numPax'])!.value,
      price: this.editForm.get(['price'])!.value,
      payment: this.editForm.get(['payment'])!.value,
      hotelDuration: this.editForm.get(['hotelDuration'])!.value,
      carDuration: this.editForm.get(['carDuration'])!.value,
      status: this.editForm.get(['status'])!.value,
      car: this.editForm.get(['car'])!.value,
      flight: this.editForm.get(['flight'])!.value,
      hotelRoom: this.editForm.get(['hotelRoom'])!.value,
    };
  }
}

<div class="row justify-content-center">
  <div class="col-8">
    <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
      <h2
        id="jhi-travel-plan-heading"
        data-cy="TravelPlanCreateUpdateHeading"
        jhiTranslate="travelTutorialCompleteApp.travelPlan.home.createOrEditLabel"
      >
        Create or edit a Travel Plan
      </h2>

      <div>
        <jhi-alert-error></jhi-alert-error>

        <div class="form-group" [hidden]="editForm.get('id')!.value == null">
          <label class="form-control-label" jhiTranslate="global.field.id" for="field_id">ID</label>
          <input type="number" class="form-control" name="id" id="field_id" data-cy="id" formControlName="id" [readonly]="true" />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="travelTutorialCompleteApp.travelPlan.name" for="field_name">Name</label>
          <input type="text" class="form-control" name="name" id="field_name" data-cy="name" formControlName="name" />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="travelTutorialCompleteApp.travelPlan.startDate" for="field_startDate"
            >Start Date</label
          >
          <div class="input-group">
            <input
              id="field_startDate"
              data-cy="startDate"
              type="text"
              class="form-control"
              name="startDate"
              ngbDatepicker
              #startDateDp="ngbDatepicker"
              formControlName="startDate"
            />
            <span class="input-group-append">
              <button type="button" class="btn btn-secondary" (click)="startDateDp.toggle()">
                <fa-icon icon="calendar-alt"></fa-icon>
              </button>
            </span>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="travelTutorialCompleteApp.travelPlan.endDate" for="field_endDate">End Date</label>
          <div class="input-group">
            <input
              id="field_endDate"
              data-cy="endDate"
              type="text"
              class="form-control"
              name="endDate"
              ngbDatepicker
              #endDateDp="ngbDatepicker"
              formControlName="endDate"
            />
            <span class="input-group-append">
              <button type="button" class="btn btn-secondary" (click)="endDateDp.toggle()"><fa-icon icon="calendar-alt"></fa-icon></button>
            </span>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="travelTutorialCompleteApp.travelPlan.numPax" for="field_numPax">Num Pax</label>
          <input type="number" class="form-control" name="numPax" id="field_numPax" data-cy="numPax" formControlName="numPax" />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="travelTutorialCompleteApp.travelPlan.price" for="field_price">Price</label>
          <input type="number" class="form-control" name="price" id="field_price" data-cy="price" formControlName="price" />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="travelTutorialCompleteApp.travelPlan.payment" for="field_payment">Payment</label>
          <input type="text" class="form-control" name="payment" id="field_payment" data-cy="payment" formControlName="payment" />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="travelTutorialCompleteApp.travelPlan.hotelDuration" for="field_hotelDuration"
            >Hotel Duration</label
          >
          <input
            type="number"
            class="form-control"
            name="hotelDuration"
            id="field_hotelDuration"
            data-cy="hotelDuration"
            formControlName="hotelDuration"
          />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="travelTutorialCompleteApp.travelPlan.carDuration" for="field_carDuration"
            >Car Duration</label
          >
          <input
            type="number"
            class="form-control"
            name="carDuration"
            id="field_carDuration"
            data-cy="carDuration"
            formControlName="carDuration"
          />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="travelTutorialCompleteApp.travelPlan.status" for="field_status">Status</label>
          <select class="form-control" name="status" formControlName="status" id="field_status" data-cy="status">
            <option [ngValue]="null">{{ 'travelTutorialCompleteApp.PlanStatus.null' | translate }}</option>
            <option value="UNKNOWN">{{ 'travelTutorialCompleteApp.PlanStatus.UNKNOWN' | translate }}</option>
            <option value="CANCELED">{{ 'travelTutorialCompleteApp.PlanStatus.CANCELED' | translate }}</option>
            <option value="TIMEDOUT">{{ 'travelTutorialCompleteApp.PlanStatus.TIMEDOUT' | translate }}</option>
            <option value="PAID">{{ 'travelTutorialCompleteApp.PlanStatus.PAID' | translate }}</option>
          </select>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="travelTutorialCompleteApp.travelPlan.car" for="field_car">Car</label>
          <select class="form-control" id="field_car" data-cy="car" name="car" formControlName="car">
            <option [ngValue]="null"></option>
            <option
              [ngValue]="carOption.id === editForm.get('car')!.value?.id ? editForm.get('car')!.value : carOption"
              *ngFor="let carOption of carsSharedCollection; trackBy: trackCarById"
            >
              {{ carOption.code }}
            </option>
          </select>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="travelTutorialCompleteApp.travelPlan.flight" for="field_flight">Flight</label>
          <select class="form-control" id="field_flight" data-cy="flight" name="flight" formControlName="flight">
            <option [ngValue]="null"></option>
            <option
              [ngValue]="flightOption.id === editForm.get('flight')!.value?.id ? editForm.get('flight')!.value : flightOption"
              *ngFor="let flightOption of flightsSharedCollection; trackBy: trackFlightById"
            >
              {{ flightOption.code }}
            </option>
          </select>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="travelTutorialCompleteApp.travelPlan.hotelRoom" for="field_hotelRoom"
            >Hotel Room</label
          >
          <select class="form-control" id="field_hotelRoom" data-cy="hotelRoom" name="hotelRoom" formControlName="hotelRoom">
            <option [ngValue]="null"></option>
            <option
              [ngValue]="hotelRoomOption.id === editForm.get('hotelRoom')!.value?.id ? editForm.get('hotelRoom')!.value : hotelRoomOption"
              *ngFor="let hotelRoomOption of hotelRoomsSharedCollection; trackBy: trackHotelRoomById"
            >
              {{ hotelRoomOption.code }}
            </option>
          </select>
        </div>
      </div>

      <div>
        <button type="button" id="cancel-save" class="btn btn-secondary" (click)="previousState()">
          <fa-icon icon="ban"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
        </button>

        <button
          type="submit"
          id="save-entity"
          data-cy="entityCreateSaveButton"
          [disabled]="editForm.invalid || isSaving"
          class="btn btn-primary"
        >
          <fa-icon icon="save"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
        </button>
      </div>
    </form>
  </div>
</div>
