// travelTutorialCOMPLETE/src/main/webapp/app/entities/car/car-update.vue
<template>
  <div class="row justify-content-center">
    <div class="col-8">
      <form name="editForm" role="form" novalidate v-on:submit.prevent="save()">
        <h2
          id="travelTutorialCompleteApp.car.home.createOrEditLabel"
          data-cy="CarCreateUpdateHeading"
          v-text="$t('travelTutorialCompleteApp.car.home.createOrEditLabel')"
        >
          Create or edit a Car
        </h2>
        <div>
          <div class="form-group" v-if="car.id">
            <label for="id" v-text="$t('global.field.id')">ID</label>
            <input type="text" class="form-control" id="id" name="id" v-model="car.id" readonly />
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('travelTutorialCompleteApp.car.code')" for="car-code">Code</label>
            <input
              type="text"
              class="form-control"
              name="code"
              id="car-code"
              data-cy="code"
              :class="{ valid: !$v.car.code.$invalid, invalid: $v.car.code.$invalid }"
              v-model="$v.car.code.$model"
            />
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('travelTutorialCompleteApp.car.passengers')" for="car-passengers"
              >Passengers</label
            >
            <input
              type="number"
              class="form-control"
              name="passengers"
              id="car-passengers"
              data-cy="passengers"
              :class="{ valid: !$v.car.passengers.$invalid, invalid: $v.car.passengers.$invalid }"
              v-model.number="$v.car.passengers.$model"
            />
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('travelTutorialCompleteApp.car.booked')" for="car-booked">Booked</label>
            <b-input-group class="mb-3">
              <b-input-group-prepend>
                <b-form-datepicker
                  aria-controls="car-booked"
                  v-model="$v.car.booked.$model"
                  name="booked"
                  class="form-control"
                  :locale="currentLanguage"
                  button-only
                  today-button
                  reset-button
                  close-button
                >
                </b-form-datepicker>
              </b-input-group-prepend>
              <b-form-input
                id="car-booked"
                data-cy="booked"
                type="text"
                class="form-control"
                name="booked"
                :class="{ valid: !$v.car.booked.$invalid, invalid: $v.car.booked.$invalid }"
                v-model="$v.car.booked.$model"
              />
            </b-input-group>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('travelTutorialCompleteApp.car.duration')" for="car-duration">Duration</label>
            <input
              type="number"
              class="form-control"
              name="duration"
              id="car-duration"
              data-cy="duration"
              :class="{ valid: !$v.car.duration.$invalid, invalid: $v.car.duration.$invalid }"
              v-model.number="$v.car.duration.$model"
            />
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('travelTutorialCompleteApp.car.price')" for="car-price">Price</label>
            <input
              type="number"
              class="form-control"
              name="price"
              id="car-price"
              data-cy="price"
              :class="{ valid: !$v.car.price.$invalid, invalid: $v.car.price.$invalid }"
              v-model.number="$v.car.price.$model"
            />
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('travelTutorialCompleteApp.car.carCo')" for="car-carCo">Car Co</label>
            <select class="form-control" id="car-carCo" data-cy="carCo" name="carCo" v-model="car.carCo">
              <option v-bind:value="null"></option>
              <option
                v-bind:value="car.carCo && carRentalCompanyOption.id === car.carCo.id ? car.carCo : carRentalCompanyOption"
                v-for="carRentalCompanyOption in carRentalCompanies"
                :key="carRentalCompanyOption.id"
              >
                {{ carRentalCompanyOption.name }}
              </option>
            </select>
          </div>
        </div>
        <div>
          <button type="button" id="cancel-save" class="btn btn-secondary" v-on:click="previousState()">
            <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.cancel')">Cancel</span>
          </button>
          <button
            type="submit"
            id="save-entity"
            data-cy="entityCreateSaveButton"
            :disabled="$v.car.$invalid || isSaving"
            class="btn btn-primary"
          >
            <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.save')">Save</span>
          </button>
        </div>
      </form>
    </div>
  </div>
</template>
<script lang="ts" src="./car-update.component.ts"></script>

// XXX/src/main/webapp/app/entities/car/update/car-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { FormBuilder } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { finalize, map } from 'rxjs/operators';

import { ICar, Car } from '../car.model';
import { CarService } from '../service/car.service';
import { ICarRentalCompany } from 'app/entities/car-rental-company/car-rental-company.model';
import { CarRentalCompanyService } from 'app/entities/car-rental-company/service/car-rental-company.service';

@Component({
  selector: 'jhi-car-update',
  templateUrl: './car-update.component.html',
})
export class CarUpdateComponent implements OnInit {
  isSaving = false;

  carRentalCompaniesSharedCollection: ICarRentalCompany[] = [];

  editForm = this.fb.group({
    id: [],
    code: [],
    passangers: [],
    boodked: [],
    duration: [],
    price: [],
    carCo: [],
  });

  constructor(
    protected carService: CarService,
    protected carRentalCompanyService: CarRentalCompanyService,
    protected activatedRoute: ActivatedRoute,
    protected fb: FormBuilder
  ) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ car }) => {
      this.updateForm(car);

      this.loadRelationshipsOptions();
    });
  }

  previousState(): void {
    window.history.back();
  }

  save(): void {
    this.isSaving = true;
    const car = this.createFromForm();
    if (car.id !== undefined) {
      this.subscribeToSaveResponse(this.carService.update(car));
    } else {
      this.subscribeToSaveResponse(this.carService.create(car));
    }
  }

  trackCarRentalCompanyById(index: number, item: ICarRentalCompany): number {
    return item.id!;
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<ICar>>): void {
    result.pipe(finalize(() => this.onSaveFinalize())).subscribe(
      () => this.onSaveSuccess(),
      () => this.onSaveError()
    );
  }

  protected onSaveSuccess(): void {
    this.previousState();
  }

  protected onSaveError(): void {
    // Api for inheritance.
  }

  protected onSaveFinalize(): void {
    this.isSaving = false;
  }

  protected updateForm(car: ICar): void {
    this.editForm.patchValue({
      id: car.id,
      code: car.code,
      passangers: car.passangers,
      boodked: car.boodked,
      duration: car.duration,
      price: car.price,
      carCo: car.carCo,
    });

    this.carRentalCompaniesSharedCollection = this.carRentalCompanyService.addCarRentalCompanyToCollectionIfMissing(
      this.carRentalCompaniesSharedCollection,
      car.carCo
    );
  }

  protected loadRelationshipsOptions(): void {
    this.carRentalCompanyService
      .query()
      .pipe(map((res: HttpResponse<ICarRentalCompany[]>) => res.body ?? []))
      .pipe(
        map((carRentalCompanies: ICarRentalCompany[]) =>
          this.carRentalCompanyService.addCarRentalCompanyToCollectionIfMissing(carRentalCompanies, this.editForm.get('carCo')!.value)
        )
      )
      .subscribe((carRentalCompanies: ICarRentalCompany[]) => (this.carRentalCompaniesSharedCollection = carRentalCompanies));
  }

  protected createFromForm(): ICar {
    return {
      ...new Car(),
      id: this.editForm.get(['id'])!.value,
      code: this.editForm.get(['code'])!.value,
      passangers: this.editForm.get(['passangers'])!.value,
      boodked: this.editForm.get(['boodked'])!.value,
      duration: this.editForm.get(['duration'])!.value,
      price: this.editForm.get(['price'])!.value,
      carCo: this.editForm.get(['carCo'])!.value,
    };
  }
}

<div class="row justify-content-center">
  <div class="col-8">
    <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
      <h2 id="jhi-car-heading" data-cy="CarCreateUpdateHeading" jhiTranslate="travelTutorialCompleteApp.car.home.createOrEditLabel">
        Create or edit a Car
      </h2>

      <div>
        <jhi-alert-error></jhi-alert-error>

        <div class="form-group" [hidden]="editForm.get('id')!.value == null">
          <label class="form-control-label" jhiTranslate="global.field.id" for="field_id">ID</label>
          <input type="number" class="form-control" name="id" id="field_id" data-cy="id" formControlName="id" [readonly]="true" />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="travelTutorialCompleteApp.car.code" for="field_code">Code</label>
          <input type="text" class="form-control" name="code" id="field_code" data-cy="code" formControlName="code" />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="travelTutorialCompleteApp.car.passangers" for="field_passangers"
            >Passangers</label
          >
          <input
            type="number"
            class="form-control"
            name="passangers"
            id="field_passangers"
            data-cy="passangers"
            formControlName="passangers"
          />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="travelTutorialCompleteApp.car.boodked" for="field_boodked">Boodked</label>
          <div class="input-group">
            <input
              id="field_boodked"
              data-cy="boodked"
              type="text"
              class="form-control"
              name="boodked"
              ngbDatepicker
              #boodkedDp="ngbDatepicker"
              formControlName="boodked"
            />
            <span class="input-group-append">
              <button type="button" class="btn btn-secondary" (click)="boodkedDp.toggle()"><fa-icon icon="calendar-alt"></fa-icon></button>
            </span>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="travelTutorialCompleteApp.car.duration" for="field_duration">Duration</label>
          <input type="number" class="form-control" name="duration" id="field_duration" data-cy="duration" formControlName="duration" />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="travelTutorialCompleteApp.car.price" for="field_price">Price</label>
          <input type="number" class="form-control" name="price" id="field_price" data-cy="price" formControlName="price" />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="travelTutorialCompleteApp.car.carCo" for="field_carCo">Car Co</label>
          <select class="form-control" id="field_carCo" data-cy="carCo" name="carCo" formControlName="carCo">
            <option [ngValue]="null"></option>
            <option
              [ngValue]="
                carRentalCompanyOption.id === editForm.get('carCo')!.value?.id ? editForm.get('carCo')!.value : carRentalCompanyOption
              "
              *ngFor="let carRentalCompanyOption of carRentalCompaniesSharedCollection; trackBy: trackCarRentalCompanyById"
            >
              {{ carRentalCompanyOption.code }}
            </option>
          </select>
        </div>
      </div>

      <div>
        <button type="button" id="cancel-save" class="btn btn-secondary" (click)="previousState()">
          <fa-icon icon="ban"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
        </button>

        <button
          type="submit"
          id="save-entity"
          data-cy="entityCreateSaveButton"
          [disabled]="editForm.invalid || isSaving"
          class="btn btn-primary"
        >
          <fa-icon icon="save"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
        </button>
      </div>
    </form>
  </div>
</div>
