// travelTutorialCOMPLETE/src/main/webapp/app/entities/traveler/traveler.vue
<template>
  <div>
    <h2 id="page-heading" data-cy="TravelerHeading">
      <span v-text="$t('travelTutorialCompleteApp.traveler.home.title')" id="traveler-heading">Travelers</span>
      <div class="d-flex justify-content-end">
        <button class="btn btn-info mr-2" v-on:click="handleSyncList" :disabled="isFetching">
          <font-awesome-icon icon="sync" :spin="isFetching"></font-awesome-icon>
          <span v-text="$t('travelTutorialCompleteApp.traveler.home.refreshListLabel')">Refresh List</span>
        </button>
        <router-link :to="{ name: 'TravelerCreate' }" custom v-slot="{ navigate }">
          <button
            @click="navigate"
            id="jh-create-entity"
            data-cy="entityCreateButton"
            class="btn btn-primary jh-create-entity create-traveler"
          >
            <font-awesome-icon icon="plus"></font-awesome-icon>
            <span v-text="$t('travelTutorialCompleteApp.traveler.home.createLabel')"> Create a new Traveler </span>
          </button>
        </router-link>
      </div>
    </h2>
    <br />
    <div class="alert alert-warning" v-if="!isFetching && travelers && travelers.length === 0">
      <span v-text="$t('travelTutorialCompleteApp.traveler.home.notFound')">No travelers found</span>
    </div>
    <div class="table-responsive" v-if="travelers && travelers.length > 0">
      <table class="table table-striped" aria-describedby="travelers">
        <thead>
          <tr>
            <th scope="row"><span v-text="$t('global.field.id')">ID</span></th>
            <th scope="row"><span v-text="$t('travelTutorialCompleteApp.traveler.name')">Name</span></th>
            <th scope="row"><span v-text="$t('travelTutorialCompleteApp.traveler.age')">Age</span></th>
            <th scope="row"></th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="traveler in travelers" :key="traveler.id" data-cy="entityTable">
            <td>
              <router-link :to="{ name: 'TravelerView', params: { travelerId: traveler.id } }">{{ traveler.id }}</router-link>
            </td>
            <td>{{ traveler.name }}</td>
            <td>{{ traveler.age }}</td>
            <td class="text-right">
              <div class="btn-group">
                <router-link :to="{ name: 'TravelerView', params: { travelerId: traveler.id } }" custom v-slot="{ navigate }">
                  <button @click="navigate" class="btn btn-info btn-sm details" data-cy="entityDetailsButton">
                    <font-awesome-icon icon="eye"></font-awesome-icon>
                    <span class="d-none d-md-inline" v-text="$t('entity.action.view')">View</span>
                  </button>
                </router-link>
                <router-link :to="{ name: 'TravelerEdit', params: { travelerId: traveler.id } }" custom v-slot="{ navigate }">
                  <button @click="navigate" class="btn btn-primary btn-sm edit" data-cy="entityEditButton">
                    <font-awesome-icon icon="pencil-alt"></font-awesome-icon>
                    <span class="d-none d-md-inline" v-text="$t('entity.action.edit')">Edit</span>
                  </button>
                </router-link>
                <b-button
                  v-on:click="prepareRemove(traveler)"
                  variant="danger"
                  class="btn btn-sm"
                  data-cy="entityDeleteButton"
                  v-b-modal.removeEntity
                >
                  <font-awesome-icon icon="times"></font-awesome-icon>
                  <span class="d-none d-md-inline" v-text="$t('entity.action.delete')">Delete</span>
                </b-button>
              </div>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
    <b-modal ref="removeEntity" id="removeEntity">
      <span slot="modal-title"
        ><span
          id="travelTutorialCompleteApp.traveler.delete.question"
          data-cy="travelerDeleteDialogHeading"
          v-text="$t('entity.delete.title')"
          >Confirm delete operation</span
        ></span
      >
      <div class="modal-body">
        <p id="jhi-delete-traveler-heading" v-text="$t('travelTutorialCompleteApp.traveler.delete.question', { id: removeId })">
          Are you sure you want to delete this Traveler?
        </p>
      </div>
      <div slot="modal-footer">
        <button type="button" class="btn btn-secondary" v-text="$t('entity.action.cancel')" v-on:click="closeDialog()">Cancel</button>
        <button
          type="button"
          class="btn btn-primary"
          id="jhi-confirm-delete-traveler"
          data-cy="entityConfirmDeleteButton"
          v-text="$t('entity.action.delete')"
          v-on:click="removeTraveler()"
        >
          Delete
        </button>
      </div>
    </b-modal>
  </div>
</template>

<script lang="ts" src="./traveler.component.ts"></script>

// XXX/src/main/webapp/app/entities/traveler/list/traveler.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { ITraveler } from '../traveler.model';
import { TravelerService } from '../service/traveler.service';
import { TravelerDeleteDialogComponent } from '../delete/traveler-delete-dialog.component';

@Component({
  selector: 'jhi-traveler',
  templateUrl: './traveler.component.html',
})
export class TravelerComponent implements OnInit {
  travelers?: ITraveler[];
  isLoading = false;

  constructor(protected travelerService: TravelerService, protected modalService: NgbModal) {}

  loadAll(): void {
    this.isLoading = true;

    this.travelerService.query().subscribe(
      (res: HttpResponse<ITraveler[]>) => {
        this.isLoading = false;
        this.travelers = res.body ?? [];
      },
      () => {
        this.isLoading = false;
      }
    );
  }

  ngOnInit(): void {
    this.loadAll();
  }

  trackId(index: number, item: ITraveler): number {
    return item.id!;
  }

  delete(traveler: ITraveler): void {
    const modalRef = this.modalService.open(TravelerDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.traveler = traveler;
    // unsubscribe not needed because closed completes on modal close
    modalRef.closed.subscribe(reason => {
      if (reason === 'deleted') {
        this.loadAll();
      }
    });
  }
}

<div>
  <h2 id="page-heading" data-cy="TravelerHeading">
    <span jhiTranslate="travelTutorialCompleteApp.traveler.home.title">Travelers</span>

    <div class="d-flex justify-content-end">
      <button class="btn btn-info mr-2" (click)="loadAll()" [disabled]="isLoading">
        <fa-icon icon="sync" [spin]="isLoading"></fa-icon>
        <span jhiTranslate="travelTutorialCompleteApp.traveler.home.refreshListLabel">Refresh List</span>
      </button>

      <button
        id="jh-create-entity"
        data-cy="entityCreateButton"
        class="btn btn-primary jh-create-entity create-traveler"
        [routerLink]="['/traveler/new']"
      >
        <fa-icon icon="plus"></fa-icon>
        <span jhiTranslate="travelTutorialCompleteApp.traveler.home.createLabel"> Create a new Traveler </span>
      </button>
    </div>
  </h2>

  <jhi-alert-error></jhi-alert-error>

  <jhi-alert></jhi-alert>

  <div class="alert alert-warning" id="no-result" *ngIf="travelers?.length === 0">
    <span jhiTranslate="travelTutorialCompleteApp.traveler.home.notFound">No travelers found</span>
  </div>

  <div class="table-responsive" id="entities" *ngIf="travelers && travelers.length > 0">
    <table class="table table-striped" aria-describedby="page-heading">
      <thead>
        <tr>
          <th scope="col"><span jhiTranslate="global.field.id">ID</span></th>
          <th scope="col"><span jhiTranslate="travelTutorialCompleteApp.traveler.name">Name</span></th>
          <th scope="col"><span jhiTranslate="travelTutorialCompleteApp.traveler.age">Age</span></th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let traveler of travelers; trackBy: trackId" data-cy="entityTable">
          <td>
            <a [routerLink]="['/traveler', traveler.id, 'view']">{{ traveler.id }}</a>
          </td>
          <td>{{ traveler.name }}</td>
          <td>{{ traveler.age }}</td>
          <td class="text-right">
            <div class="btn-group">
              <button
                type="submit"
                [routerLink]="['/traveler', traveler.id, 'view']"
                class="btn btn-info btn-sm"
                data-cy="entityDetailsButton"
              >
                <fa-icon icon="eye"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
              </button>

              <button
                type="submit"
                [routerLink]="['/traveler', traveler.id, 'edit']"
                class="btn btn-primary btn-sm"
                data-cy="entityEditButton"
              >
                <fa-icon icon="pencil-alt"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
              </button>

              <button type="submit" (click)="delete(traveler)" class="btn btn-danger btn-sm" data-cy="entityDeleteButton">
                <fa-icon icon="times"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
              </button>
            </div>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
