// travelTutorialCOMPLETE/src/main/webapp/app/entities/flight/flight-update.vue
<template>
  <div class="row justify-content-center">
    <div class="col-8">
      <form name="editForm" role="form" novalidate v-on:submit.prevent="save()">
        <h2
          id="travelTutorialCompleteApp.flight.home.createOrEditLabel"
          data-cy="FlightCreateUpdateHeading"
          v-text="$t('travelTutorialCompleteApp.flight.home.createOrEditLabel')"
        >
          Create or edit a Flight
        </h2>
        <div>
          <div class="form-group" v-if="flight.id">
            <label for="id" v-text="$t('global.field.id')">ID</label>
            <input type="text" class="form-control" id="id" name="id" v-model="flight.id" readonly />
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('travelTutorialCompleteApp.flight.code')" for="flight-code">Code</label>
            <input
              type="text"
              class="form-control"
              name="code"
              id="flight-code"
              data-cy="code"
              :class="{ valid: !$v.flight.code.$invalid, invalid: $v.flight.code.$invalid }"
              v-model="$v.flight.code.$model"
              required
            />
            <div v-if="$v.flight.code.$anyDirty && $v.flight.code.$invalid">
              <small class="form-text text-danger" v-if="!$v.flight.code.required" v-text="$t('entity.validation.required')">
                This field is required.
              </small>
              <small class="form-text text-danger" v-if="!$v.flight.code.minLength" v-text="$t('entity.validation.minlength', { min: 3 })">
                This field is required to be at least 3 characters.
              </small>
              <small class="form-text text-danger" v-if="!$v.flight.code.maxLength" v-text="$t('entity.validation.maxlength', { max: 3 })">
                This field cannot be longer than 3 characters.
              </small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('travelTutorialCompleteApp.flight.departure')" for="flight-departure"
              >Departure</label
            >
            <div class="d-flex">
              <input
                id="flight-departure"
                data-cy="departure"
                type="datetime-local"
                class="form-control"
                name="departure"
                :class="{ valid: !$v.flight.departure.$invalid, invalid: $v.flight.departure.$invalid }"
                required
                :value="convertDateTimeFromServer($v.flight.departure.$model)"
                @change="updateZonedDateTimeField('departure', $event)"
              />
            </div>
            <div v-if="$v.flight.departure.$anyDirty && $v.flight.departure.$invalid">
              <small class="form-text text-danger" v-if="!$v.flight.departure.required" v-text="$t('entity.validation.required')">
                This field is required.
              </small>
              <small
                class="form-text text-danger"
                v-if="!$v.flight.departure.ZonedDateTimelocal"
                v-text="$t('entity.validation.ZonedDateTimelocal')"
              >
                This field should be a date and time.
              </small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('travelTutorialCompleteApp.flight.duration')" for="flight-duration"
              >Duration</label
            >
            <input
              type="number"
              class="form-control"
              name="duration"
              id="flight-duration"
              data-cy="duration"
              :class="{ valid: !$v.flight.duration.$invalid, invalid: $v.flight.duration.$invalid }"
              v-model.number="$v.flight.duration.$model"
              required
            />
            <div v-if="$v.flight.duration.$anyDirty && $v.flight.duration.$invalid">
              <small class="form-text text-danger" v-if="!$v.flight.duration.required" v-text="$t('entity.validation.required')">
                This field is required.
              </small>
              <small class="form-text text-danger" v-if="!$v.flight.duration.numeric" v-text="$t('entity.validation.number')">
                This field should be a number.
              </small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('travelTutorialCompleteApp.flight.emptySeats')" for="flight-emptySeats"
              >Empty Seats</label
            >
            <input
              type="number"
              class="form-control"
              name="emptySeats"
              id="flight-emptySeats"
              data-cy="emptySeats"
              :class="{ valid: !$v.flight.emptySeats.$invalid, invalid: $v.flight.emptySeats.$invalid }"
              v-model.number="$v.flight.emptySeats.$model"
              required
            />
            <div v-if="$v.flight.emptySeats.$anyDirty && $v.flight.emptySeats.$invalid">
              <small class="form-text text-danger" v-if="!$v.flight.emptySeats.required" v-text="$t('entity.validation.required')">
                This field is required.
              </small>
              <small class="form-text text-danger" v-if="!$v.flight.emptySeats.numeric" v-text="$t('entity.validation.number')">
                This field should be a number.
              </small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('travelTutorialCompleteApp.flight.price')" for="flight-price">Price</label>
            <input
              type="number"
              class="form-control"
              name="price"
              id="flight-price"
              data-cy="price"
              :class="{ valid: !$v.flight.price.$invalid, invalid: $v.flight.price.$invalid }"
              v-model.number="$v.flight.price.$model"
            />
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('travelTutorialCompleteApp.flight.from')" for="flight-from">From</label>
            <select class="form-control" id="flight-from" data-cy="from" name="from" v-model="flight.from">
              <option v-bind:value="null"></option>
              <option
                v-bind:value="flight.from && airportOption.id === flight.from.id ? flight.from : airportOption"
                v-for="airportOption in airports"
                :key="airportOption.id"
              >
                {{ airportOption.code }}
              </option>
            </select>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('travelTutorialCompleteApp.flight.to')" for="flight-to">To</label>
            <select class="form-control" id="flight-to" data-cy="to" name="to" v-model="flight.to">
              <option v-bind:value="null"></option>
              <option
                v-bind:value="flight.to && airportOption.id === flight.to.id ? flight.to : airportOption"
                v-for="airportOption in airports"
                :key="airportOption.id"
              >
                {{ airportOption.code }}
              </option>
            </select>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('travelTutorialCompleteApp.flight.airline')" for="flight-airline">Airline</label>
            <select class="form-control" id="flight-airline" data-cy="airline" name="airline" v-model="flight.airline">
              <option v-bind:value="null"></option>
              <option
                v-bind:value="flight.airline && airlineCompanyOption.id === flight.airline.id ? flight.airline : airlineCompanyOption"
                v-for="airlineCompanyOption in airlineCompanies"
                :key="airlineCompanyOption.id"
              >
                {{ airlineCompanyOption.code }}
              </option>
            </select>
          </div>
        </div>
        <div>
          <button type="button" id="cancel-save" class="btn btn-secondary" v-on:click="previousState()">
            <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.cancel')">Cancel</span>
          </button>
          <button
            type="submit"
            id="save-entity"
            data-cy="entityCreateSaveButton"
            :disabled="$v.flight.$invalid || isSaving"
            class="btn btn-primary"
          >
            <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.save')">Save</span>
          </button>
        </div>
      </form>
    </div>
  </div>
</template>
<script lang="ts" src="./flight-update.component.ts"></script>

// XXX/src/main/webapp/app/entities/flight/update/flight-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { finalize, map } from 'rxjs/operators';

import * as dayjs from 'dayjs';
import { DATE_TIME_FORMAT } from 'app/config/input.constants';

import { IFlight, Flight } from '../flight.model';
import { FlightService } from '../service/flight.service';
import { IAirport } from 'app/entities/airport/airport.model';
import { AirportService } from 'app/entities/airport/service/airport.service';
import { IAirlineCompany } from 'app/entities/airline-company/airline-company.model';
import { AirlineCompanyService } from 'app/entities/airline-company/service/airline-company.service';

@Component({
  selector: 'jhi-flight-update',
  templateUrl: './flight-update.component.html',
})
export class FlightUpdateComponent implements OnInit {
  isSaving = false;

  airportsSharedCollection: IAirport[] = [];
  airlineCompaniesSharedCollection: IAirlineCompany[] = [];

  editForm = this.fb.group({
    id: [],
    code: [null, [Validators.required, Validators.minLength(3), Validators.maxLength(3)]],
    departure: [null, [Validators.required]],
    duration: [null, [Validators.required]],
    emptySeats: [null, [Validators.required]],
    price: [],
    from: [],
    to: [],
    airline: [],
  });

  constructor(
    protected flightService: FlightService,
    protected airportService: AirportService,
    protected airlineCompanyService: AirlineCompanyService,
    protected activatedRoute: ActivatedRoute,
    protected fb: FormBuilder
  ) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ flight }) => {
      if (flight.id === undefined) {
        const today = dayjs().startOf('day');
        flight.departure = today;
      }

      this.updateForm(flight);

      this.loadRelationshipsOptions();
    });
  }

  previousState(): void {
    window.history.back();
  }

  save(): void {
    this.isSaving = true;
    const flight = this.createFromForm();
    if (flight.id !== undefined) {
      this.subscribeToSaveResponse(this.flightService.update(flight));
    } else {
      this.subscribeToSaveResponse(this.flightService.create(flight));
    }
  }

  trackAirportById(index: number, item: IAirport): number {
    return item.id!;
  }

  trackAirlineCompanyById(index: number, item: IAirlineCompany): number {
    return item.id!;
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<IFlight>>): void {
    result.pipe(finalize(() => this.onSaveFinalize())).subscribe(
      () => this.onSaveSuccess(),
      () => this.onSaveError()
    );
  }

  protected onSaveSuccess(): void {
    this.previousState();
  }

  protected onSaveError(): void {
    // Api for inheritance.
  }

  protected onSaveFinalize(): void {
    this.isSaving = false;
  }

  protected updateForm(flight: IFlight): void {
    this.editForm.patchValue({
      id: flight.id,
      code: flight.code,
      departure: flight.departure ? flight.departure.format(DATE_TIME_FORMAT) : null,
      duration: flight.duration,
      emptySeats: flight.emptySeats,
      price: flight.price,
      from: flight.from,
      to: flight.to,
      airline: flight.airline,
    });

    this.airportsSharedCollection = this.airportService.addAirportToCollectionIfMissing(
      this.airportsSharedCollection,
      flight.from,
      flight.to
    );
    this.airlineCompaniesSharedCollection = this.airlineCompanyService.addAirlineCompanyToCollectionIfMissing(
      this.airlineCompaniesSharedCollection,
      flight.airline
    );
  }

  protected loadRelationshipsOptions(): void {
    this.airportService
      .query()
      .pipe(map((res: HttpResponse<IAirport[]>) => res.body ?? []))
      .pipe(
        map((airports: IAirport[]) =>
          this.airportService.addAirportToCollectionIfMissing(airports, this.editForm.get('from')!.value, this.editForm.get('to')!.value)
        )
      )
      .subscribe((airports: IAirport[]) => (this.airportsSharedCollection = airports));

    this.airlineCompanyService
      .query()
      .pipe(map((res: HttpResponse<IAirlineCompany[]>) => res.body ?? []))
      .pipe(
        map((airlineCompanies: IAirlineCompany[]) =>
          this.airlineCompanyService.addAirlineCompanyToCollectionIfMissing(airlineCompanies, this.editForm.get('airline')!.value)
        )
      )
      .subscribe((airlineCompanies: IAirlineCompany[]) => (this.airlineCompaniesSharedCollection = airlineCompanies));
  }

  protected createFromForm(): IFlight {
    return {
      ...new Flight(),
      id: this.editForm.get(['id'])!.value,
      code: this.editForm.get(['code'])!.value,
      departure: this.editForm.get(['departure'])!.value ? dayjs(this.editForm.get(['departure'])!.value, DATE_TIME_FORMAT) : undefined,
      duration: this.editForm.get(['duration'])!.value,
      emptySeats: this.editForm.get(['emptySeats'])!.value,
      price: this.editForm.get(['price'])!.value,
      from: this.editForm.get(['from'])!.value,
      to: this.editForm.get(['to'])!.value,
      airline: this.editForm.get(['airline'])!.value,
    };
  }
}

<div class="row justify-content-center">
  <div class="col-8">
    <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
      <h2
        id="jhi-flight-heading"
        data-cy="FlightCreateUpdateHeading"
        jhiTranslate="travelTutorialCompleteApp.flight.home.createOrEditLabel"
      >
        Create or edit a Flight
      </h2>

      <div>
        <jhi-alert-error></jhi-alert-error>

        <div class="form-group" [hidden]="editForm.get('id')!.value == null">
          <label class="form-control-label" jhiTranslate="global.field.id" for="field_id">ID</label>
          <input type="number" class="form-control" name="id" id="field_id" data-cy="id" formControlName="id" [readonly]="true" />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="travelTutorialCompleteApp.flight.code" for="field_code">Code</label>
          <input type="text" class="form-control" name="code" id="field_code" data-cy="code" formControlName="code" />
          <div *ngIf="editForm.get('code')!.invalid && (editForm.get('code')!.dirty || editForm.get('code')!.touched)">
            <small class="form-text text-danger" *ngIf="editForm.get('code')?.errors?.required" jhiTranslate="entity.validation.required">
              This field is required.
            </small>
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('code')?.errors?.minlength"
              jhiTranslate="entity.validation.minlength"
              [translateValues]="{ min: 3 }"
            >
              This field is required to be at least 3 characters.
            </small>
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('code')?.errors?.maxlength"
              jhiTranslate="entity.validation.maxlength"
              [translateValues]="{ max: 3 }"
            >
              This field cannot be longer than 3 characters.
            </small>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="travelTutorialCompleteApp.flight.departure" for="field_departure"
            >Departure</label
          >
          <div class="d-flex">
            <input
              id="field_departure"
              data-cy="departure"
              type="datetime-local"
              class="form-control"
              name="departure"
              formControlName="departure"
              placeholder="YYYY-MM-DD HH:mm"
            />
          </div>
          <div *ngIf="editForm.get('departure')!.invalid && (editForm.get('departure')!.dirty || editForm.get('departure')!.touched)">
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('departure')?.errors?.required"
              jhiTranslate="entity.validation.required"
            >
              This field is required.
            </small>
            <small
              class="form-text text-danger"
              [hidden]="!editForm.get('departure')?.errors?.ZonedDateTimelocal"
              jhiTranslate="entity.validation.ZonedDateTimelocal"
            >
              This field should be a date and time.
            </small>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="travelTutorialCompleteApp.flight.duration" for="field_duration">Duration</label>
          <input type="number" class="form-control" name="duration" id="field_duration" data-cy="duration" formControlName="duration" />
          <div *ngIf="editForm.get('duration')!.invalid && (editForm.get('duration')!.dirty || editForm.get('duration')!.touched)">
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('duration')?.errors?.required"
              jhiTranslate="entity.validation.required"
            >
              This field is required.
            </small>
            <small
              class="form-text text-danger"
              [hidden]="!editForm.get('duration')?.errors?.number"
              jhiTranslate="entity.validation.number"
            >
              This field should be a number.
            </small>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="travelTutorialCompleteApp.flight.emptySeats" for="field_emptySeats"
            >Empty Seats</label
          >
          <input
            type="number"
            class="form-control"
            name="emptySeats"
            id="field_emptySeats"
            data-cy="emptySeats"
            formControlName="emptySeats"
          />
          <div *ngIf="editForm.get('emptySeats')!.invalid && (editForm.get('emptySeats')!.dirty || editForm.get('emptySeats')!.touched)">
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('emptySeats')?.errors?.required"
              jhiTranslate="entity.validation.required"
            >
              This field is required.
            </small>
            <small
              class="form-text text-danger"
              [hidden]="!editForm.get('emptySeats')?.errors?.number"
              jhiTranslate="entity.validation.number"
            >
              This field should be a number.
            </small>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="travelTutorialCompleteApp.flight.price" for="field_price">Price</label>
          <input type="number" class="form-control" name="price" id="field_price" data-cy="price" formControlName="price" />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="travelTutorialCompleteApp.flight.from" for="field_from">From</label>
          <select class="form-control" id="field_from" data-cy="from" name="from" formControlName="from">
            <option [ngValue]="null"></option>
            <option
              [ngValue]="airportOption.id === editForm.get('from')!.value?.id ? editForm.get('from')!.value : airportOption"
              *ngFor="let airportOption of airportsSharedCollection; trackBy: trackAirportById"
            >
              {{ airportOption.code }}
            </option>
          </select>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="travelTutorialCompleteApp.flight.to" for="field_to">To</label>
          <select class="form-control" id="field_to" data-cy="to" name="to" formControlName="to">
            <option [ngValue]="null"></option>
            <option
              [ngValue]="airportOption.id === editForm.get('to')!.value?.id ? editForm.get('to')!.value : airportOption"
              *ngFor="let airportOption of airportsSharedCollection; trackBy: trackAirportById"
            >
              {{ airportOption.code }}
            </option>
          </select>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="travelTutorialCompleteApp.flight.airline" for="field_airline">Airline</label>
          <select class="form-control" id="field_airline" data-cy="airline" name="airline" formControlName="airline">
            <option [ngValue]="null"></option>
            <option
              [ngValue]="
                airlineCompanyOption.id === editForm.get('airline')!.value?.id ? editForm.get('airline')!.value : airlineCompanyOption
              "
              *ngFor="let airlineCompanyOption of airlineCompaniesSharedCollection; trackBy: trackAirlineCompanyById"
            >
              {{ airlineCompanyOption.code }}
            </option>
          </select>
        </div>
      </div>

      <div>
        <button type="button" id="cancel-save" class="btn btn-secondary" (click)="previousState()">
          <fa-icon icon="ban"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
        </button>

        <button
          type="submit"
          id="save-entity"
          data-cy="entityCreateSaveButton"
          [disabled]="editForm.invalid || isSaving"
          class="btn btn-primary"
        >
          <fa-icon icon="save"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
        </button>
      </div>
    </form>
  </div>
</div>
