// XXX/src/main/webapp/app/entities/traveler/update/traveler-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { finalize } from 'rxjs/operators';

import { ITraveler, Traveler } from '../traveler.model';
import { TravelerService } from '../service/traveler.service';

@Component({
  selector: 'jhi-traveler-update',
  templateUrl: './traveler-update.component.html',
})
export class TravelerUpdateComponent implements OnInit {
  isSaving = false;

  editForm = this.fb.group({
    id: [],
    name: [],
    age: [null, [Validators.required, Validators.min(0), Validators.max(200)]],
  });

  constructor(protected travelerService: TravelerService, protected activatedRoute: ActivatedRoute, protected fb: FormBuilder) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ traveler }) => {
      this.updateForm(traveler);
    });
  }

  previousState(): void {
    window.history.back();
  }

  save(): void {
    this.isSaving = true;
    const traveler = this.createFromForm();
    if (traveler.id !== undefined) {
      this.subscribeToSaveResponse(this.travelerService.update(traveler));
    } else {
      this.subscribeToSaveResponse(this.travelerService.create(traveler));
    }
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<ITraveler>>): void {
    result.pipe(finalize(() => this.onSaveFinalize())).subscribe(
      () => this.onSaveSuccess(),
      () => this.onSaveError()
    );
  }

  protected onSaveSuccess(): void {
    this.previousState();
  }

  protected onSaveError(): void {
    // Api for inheritance.
  }

  protected onSaveFinalize(): void {
    this.isSaving = false;
  }

  protected updateForm(traveler: ITraveler): void {
    this.editForm.patchValue({
      id: traveler.id,
      name: traveler.name,
      age: traveler.age,
    });
  }

  protected createFromForm(): ITraveler {
    return {
      ...new Traveler(),
      id: this.editForm.get(['id'])!.value,
      name: this.editForm.get(['name'])!.value,
      age: this.editForm.get(['age'])!.value,
    };
  }
}

<div class="row justify-content-center">
  <div class="col-8">
    <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
      <h2
        id="jhi-traveler-heading"
        data-cy="TravelerCreateUpdateHeading"
        jhiTranslate="travelTutorialCompleteApp.traveler.home.createOrEditLabel"
      >
        Create or edit a Traveler
      </h2>

      <div>
        <jhi-alert-error></jhi-alert-error>

        <div class="form-group" [hidden]="editForm.get('id')!.value == null">
          <label class="form-control-label" jhiTranslate="global.field.id" for="field_id">ID</label>
          <input type="number" class="form-control" name="id" id="field_id" data-cy="id" formControlName="id" [readonly]="true" />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="travelTutorialCompleteApp.traveler.name" for="field_name">Name</label>
          <input type="text" class="form-control" name="name" id="field_name" data-cy="name" formControlName="name" />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="travelTutorialCompleteApp.traveler.age" for="field_age">Age</label>
          <input type="number" class="form-control" name="age" id="field_age" data-cy="age" formControlName="age" />
          <div *ngIf="editForm.get('age')!.invalid && (editForm.get('age')!.dirty || editForm.get('age')!.touched)">
            <small class="form-text text-danger" *ngIf="editForm.get('age')?.errors?.required" jhiTranslate="entity.validation.required">
              This field is required.
            </small>
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('age')?.errors?.min"
              jhiTranslate="entity.validation.min"
              [translateValues]="{ min: 0 }"
            >
              This field should be at least 0.
            </small>
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('age')?.errors?.max"
              jhiTranslate="entity.validation.max"
              [translateValues]="{ max: 200 }"
            >
              This field cannot be more than 200.
            </small>
            <small class="form-text text-danger" [hidden]="!editForm.get('age')?.errors?.number" jhiTranslate="entity.validation.number">
              This field should be a number.
            </small>
          </div>
        </div>
      </div>

      <div>
        <button type="button" id="cancel-save" class="btn btn-secondary" (click)="previousState()">
          <fa-icon icon="ban"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
        </button>

        <button
          type="submit"
          id="save-entity"
          data-cy="entityCreateSaveButton"
          [disabled]="editForm.invalid || isSaving"
          class="btn btn-primary"
        >
          <fa-icon icon="save"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
        </button>
      </div>
    </form>
  </div>
</div>

// travelTutorialCOMPLETE/src/main/webapp/app/entities/traveler/traveler-update.vue
<template>
  <div class="row justify-content-center">
    <div class="col-8">
      <form name="editForm" role="form" novalidate v-on:submit.prevent="save()">
        <h2
          id="travelTutorialCompleteApp.traveler.home.createOrEditLabel"
          data-cy="TravelerCreateUpdateHeading"
          v-text="$t('travelTutorialCompleteApp.traveler.home.createOrEditLabel')"
        >
          Create or edit a Traveler
        </h2>
        <div>
          <div class="form-group" v-if="traveler.id">
            <label for="id" v-text="$t('global.field.id')">ID</label>
            <input type="text" class="form-control" id="id" name="id" v-model="traveler.id" readonly />
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('travelTutorialCompleteApp.traveler.name')" for="traveler-name">Name</label>
            <input
              type="text"
              class="form-control"
              name="name"
              id="traveler-name"
              data-cy="name"
              :class="{ valid: !$v.traveler.name.$invalid, invalid: $v.traveler.name.$invalid }"
              v-model="$v.traveler.name.$model"
            />
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('travelTutorialCompleteApp.traveler.age')" for="traveler-age">Age</label>
            <input
              type="number"
              class="form-control"
              name="age"
              id="traveler-age"
              data-cy="age"
              :class="{ valid: !$v.traveler.age.$invalid, invalid: $v.traveler.age.$invalid }"
              v-model.number="$v.traveler.age.$model"
              required
            />
            <div v-if="$v.traveler.age.$anyDirty && $v.traveler.age.$invalid">
              <small class="form-text text-danger" v-if="!$v.traveler.age.required" v-text="$t('entity.validation.required')">
                This field is required.
              </small>
              <small class="form-text text-danger" v-if="!$v.traveler.age.min" v-text="$t('entity.validation.min', { min: 0 })">
                This field should be at least 0.
              </small>
              <small class="form-text text-danger" v-if="!$v.traveler.age.max" v-text="$t('entity.validation.max', { max: 200 })">
                This field cannot be longer than 200 characters.
              </small>
              <small class="form-text text-danger" v-if="!$v.traveler.age.numeric" v-text="$t('entity.validation.number')">
                This field should be a number.
              </small>
            </div>
          </div>
        </div>
        <div>
          <button type="button" id="cancel-save" class="btn btn-secondary" v-on:click="previousState()">
            <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.cancel')">Cancel</span>
          </button>
          <button
            type="submit"
            id="save-entity"
            data-cy="entityCreateSaveButton"
            :disabled="$v.traveler.$invalid || isSaving"
            class="btn btn-primary"
          >
            <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.save')">Save</span>
          </button>
        </div>
      </form>
    </div>
  </div>
</template>
<script lang="ts" src="./traveler-update.component.ts"></script>
